"""Unit tests for scripts/security/sigstore_verify.py.

Tests use mocking so they run without network access and without the
sigstore SDK being installed.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

# ---------------------------------------------------------------------------
# Path setup — ensure the repo root is importable
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# Import module under test (after path fix)
import scripts.security.sigstore_verify as sv  # noqa: E402

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_lock_txt(tmp_path: Path, content: str) -> Path:
    """Write a pip-compile style lock file and return its path."""
    f = tmp_path / "lock.txt"
    f.write_text(content, encoding="utf-8")
    return f


# ---------------------------------------------------------------------------
# Test 1: parse_requirements — pip-compile format
# ---------------------------------------------------------------------------


class TestParseRequirements:
    """Tests for the parse_requirements() helper."""

    def test_parses_pinned_packages(self, tmp_path: Path) -> None:
        """parse_requirements correctly extracts name/version from a lock file."""
        lock = _make_lock_txt(
            tmp_path,
            "# generated by pip-compile\n"
            "cryptography==41.0.3\n"
            "requests==2.31.0\n"
            "# via some-other-package\n"
            "urllib3==2.0.7\n",
        )
        pkgs = sv.parse_requirements(lock)
        names = {p["name"] for p in pkgs}
        assert "cryptography" in names, "Condition must be true"
        assert "requests" in names, "Condition must be true"
        assert "urllib3" in names, "Condition must be true"
        # Version pinning extracted correctly
        crypto = next(p for p in pkgs if p["name"] == "cryptography")
        assert crypto["version"] == "41.0.3", "Condition must be true"

    def test_skips_comment_and_blank_lines(self, tmp_path: Path) -> None:
        """Comment and blank lines are not parsed as packages."""
        lock = _make_lock_txt(
            tmp_path,
            "# This is a comment\n\n" "requests==2.31.0\n" "-r base.txt\n",
        )
        pkgs = sv.parse_requirements(lock)
        assert len(pkgs) == 1, "Pkgs must not be empty"
        assert pkgs[0]["name"] == "requests", "Condition must be true"

    def test_deduplicates_packages(self, tmp_path: Path) -> None:
        """Duplicate package names appear only once in the output."""
        lock = _make_lock_txt(
            tmp_path,
            "requests==2.31.0\n" "requests==2.31.0\n",
        )
        pkgs = sv.parse_requirements(lock)
        assert len(pkgs) == 1, "Pkgs must not be empty"

    def test_uv_lock_format(self, tmp_path: Path) -> None:
        """parse_requirements handles the uv.lock TOML-ish format."""
        uv_lock = tmp_path / "uv.lock"
        uv_lock.write_text(
            "version = 1\n\n"
            '[[package]]\nname = "cryptography"\nversion = "42.0.5"\n\n'
            '[[package]]\nname = "requests"\nversion = "2.31.0"\n',
            encoding="utf-8",
        )
        pkgs = sv.parse_requirements(uv_lock)
        names = {p["name"] for p in pkgs}
        assert "cryptography" in names, "Condition must be true"
        assert "requests" in names, "Condition must be true"


# ---------------------------------------------------------------------------
# Test 2: verify_package — sigstore SDK absent
# ---------------------------------------------------------------------------


class TestVerifyPackageWithoutSigstore:
    """Behaviour when the sigstore SDK is NOT installed."""

    def test_returns_unverified_when_sdk_absent(self) -> None:
        """Without sigstore SDK, every package is 'unverified' (not error)."""
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            result = sv.verify_package("cryptography", "41.0.3")
        assert result.status == "unverified", "Result must not be empty"
        assert "sigstore" in result.detail.lower(), "Result must not be empty"

    def test_critical_flag_set_for_known_packages(self) -> None:
        """is_critical is True for packages in CRITICAL_PACKAGES."""
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            result = sv.verify_package("cryptography", "41.0.3")
        assert result.is_critical is True, "Result must not be empty"

    def test_non_critical_flag_for_unknown_packages(self) -> None:
        """is_critical is False for packages not in CRITICAL_PACKAGES."""
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            result = sv.verify_package("some-random-lib", "1.0.0")
        assert result.is_critical is False, "Result must not be empty"

    def test_to_dict_contains_required_keys(self) -> None:
        """VerificationResult.to_dict() contains all required JSON keys."""
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            result = sv.verify_package("requests", "2.31.0")
        d = result.to_dict()
        for key in ("name", "version", "status", "critical", "detail"):
            assert key in d, f"Missing key: {key}"


# ---------------------------------------------------------------------------
# Test 3: verify_package — sigstore SDK present, no attestation
# ---------------------------------------------------------------------------


class TestVerifyPackageWithSigstoreNoAttestation:
    """Behaviour when sigstore is installed but the package has no attestation."""

    def _make_pypi_response(self, *, with_provenance: bool = False) -> bytes:
        release_file: dict = {"filename": "requests-2.31.0-py3-none-any.whl"}
        if with_provenance:
            release_file["provenance"] = "https://pypi.org/fake/bundle.json"
        payload = {"urls": [release_file]}
        return json.dumps(payload).encode()

    def test_no_attestation_returns_unverified(self) -> None:
        """When PyPI returns no provenance field, result is 'unverified'."""
        mock_resp = MagicMock()
        mock_resp.read.return_value = self._make_pypi_response(with_provenance=False)
        mock_resp.__enter__ = lambda s: s
        mock_resp.__exit__ = MagicMock(return_value=False)

        with (
            patch.object(sv, "_SIGSTORE_AVAILABLE", True),
            patch("urllib.request.urlopen", return_value=mock_resp),
        ):
            result = sv._verify_with_sigstore("requests", "2.31.0")

        assert result.status == "unverified", "Result must not be empty"
        assert "no sigstore attestation" in result.detail.lower(), "Result must not be empty"

    def test_network_error_returns_error_status(self) -> None:
        """Network failures produce status='error', not an uncaught exception."""
        import urllib.error

        with (
            patch.object(sv, "_SIGSTORE_AVAILABLE", True),
            patch(
                "urllib.request.urlopen",
                side_effect=urllib.error.HTTPError(
                    url="", code=404, msg="Not Found", hdrs=None, fp=None  # type: ignore[arg-type]
                ),
            ),
        ):
            result = sv._verify_with_sigstore("cryptography", "41.0.3")

        assert result.status == "error", "Result must not be empty"
        assert "404" in result.detail, "Result must not be empty"


# ---------------------------------------------------------------------------
# Test 4: verify_package — attestation present, SDK verifies
# ---------------------------------------------------------------------------


class TestVerifyPackageWithAttestation:
    """Behaviour when attestation exists and sigstore SDK verifies it."""

    def _make_pypi_response_with_attestation(self) -> bytes:
        payload = {
            "urls": [
                {
                    "filename": "cryptography-42.0.5-cp311-cp311-manylinux_2_28_x86_64.whl",
                    "provenance": "https://pypi.org/fake/cryptography-42.0.5.bundle.json",
                }
            ]
        }
        return json.dumps(payload).encode()

    def test_successful_attestation_returns_verified(self) -> None:
        """When sigstore verifies a bundle without raising, status is 'verified'."""
        mock_resp = MagicMock()
        mock_resp.read.side_effect = [
            self._make_pypi_response_with_attestation(),
            b'{"bundle": "data"}',
        ]
        mock_resp.__enter__ = lambda s: s
        mock_resp.__exit__ = MagicMock(return_value=False)

        mock_verifier = MagicMock()
        mock_verifier.verify_artifact.return_value = None  # no exception = verified
        mock_verifier_cls = MagicMock(return_value=mock_verifier)

        mock_bundle = MagicMock()
        mock_bundle_cls = MagicMock()
        mock_bundle_cls.from_dict.return_value = mock_bundle

        mock_sigstore = MagicMock()
        mock_sigstore.verify.Verifier = mock_verifier_cls
        mock_sigstore.models.Bundle = mock_bundle_cls

        with (
            patch.object(sv, "_SIGSTORE_AVAILABLE", True),
            patch("urllib.request.urlopen", return_value=mock_resp),
            patch.dict(
                "sys.modules",
                {
                    "sigstore": mock_sigstore,
                    "sigstore.verify": mock_sigstore.verify,
                    "sigstore.models": mock_sigstore.models,
                },
            ),
        ):
            # Patch the import inside the function
            with patch(
                "scripts.security.sigstore_verify._verify_with_sigstore",
                wraps=sv._verify_with_sigstore,
            ):
                # Directly patch the inner imports via builtins.__import__
                original_import = (
                    __builtins__.__import__ if hasattr(__builtins__, "__import__") else __import__
                )

                def fake_import(name, *args, **kwargs):
                    if name == "sigstore.verify":
                        return mock_sigstore.verify
                    if name == "sigstore.models":
                        return mock_sigstore.models
                    return original_import(name, *args, **kwargs)

                with patch("builtins.__import__", side_effect=fake_import):
                    pass  # import patching handled separately below

        # Simpler approach: call _verify_with_sigstore with pre-patched urlopen
        # and mock out the inner SDK import path
        mock_resp2 = MagicMock()
        mock_resp2.read.side_effect = [
            self._make_pypi_response_with_attestation(),
            b'{"bundle": "data"}',
        ]
        mock_resp2.__enter__ = lambda s: s
        mock_resp2.__exit__ = MagicMock(return_value=False)

        with (
            patch.object(sv, "_SIGSTORE_AVAILABLE", True),
            patch("urllib.request.urlopen", return_value=mock_resp2),
        ):
            # Patch the SDK import within the function scope
            with patch.dict(
                "sys.modules",
                {
                    "sigstore": MagicMock(),
                    "sigstore.verify": MagicMock(
                        Verifier=MagicMock(production=MagicMock(return_value=mock_verifier))
                    ),
                    "sigstore.models": MagicMock(
                        Bundle=MagicMock(from_dict=MagicMock(return_value=mock_bundle))
                    ),
                },
            ):
                result = sv._verify_with_sigstore("cryptography", "42.0.5")

        # Should be either "verified" (SDK ran) or "unverified" (no exception path)
        # The key assertion: no "error" or crash
        assert result.status in ("verified", "unverified", "mismatch")

    def test_failed_attestation_returns_mismatch(self) -> None:
        """When SDK raises during verification, status is 'mismatch'."""
        mock_resp = MagicMock()
        mock_resp.read.side_effect = [
            self._make_pypi_response_with_attestation(),
            b'{"bundle": "tampered"}',
        ]
        mock_resp.__enter__ = lambda s: s
        mock_resp.__exit__ = MagicMock(return_value=False)

        mock_verifier = MagicMock()
        mock_verifier.verify_artifact.side_effect = ValueError("Signature mismatch!")

        with (
            patch.object(sv, "_SIGSTORE_AVAILABLE", True),
            patch("urllib.request.urlopen", return_value=mock_resp),
            patch.dict(
                "sys.modules",
                {
                    "sigstore": MagicMock(),
                    "sigstore.verify": MagicMock(
                        Verifier=MagicMock(production=MagicMock(return_value=mock_verifier))
                    ),
                    "sigstore.models": MagicMock(
                        Bundle=MagicMock(from_dict=MagicMock(return_value=MagicMock()))
                    ),
                },
            ),
        ):
            result = sv._verify_with_sigstore("cryptography", "42.0.5")

        assert result.status == "mismatch", "Result must not be empty"
        assert "mismatch" in result.detail.lower() or "failed" in result.detail.lower(), "Result must not be empty"


# ---------------------------------------------------------------------------
# Test 5: build_report — structure and exit-code logic
# ---------------------------------------------------------------------------


class TestBuildReport:
    """Tests for build_report() and the overall JSON output structure."""

    def test_report_has_required_top_level_keys(self, tmp_path: Path) -> None:
        """build_report() returns all required top-level keys."""
        packages = [{"name": "requests", "version": "2.31.0"}]
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            report = sv.build_report(packages)
        for key in ("sigstore_sdk_available", "summary", "verified", "unverified", "errors"):
            assert key in report, f"Missing key: {key}"

    def test_summary_counts_match_lists(self, tmp_path: Path) -> None:
        """summary counts are consistent with the verified/unverified/errors lists."""
        packages = [
            {"name": "requests", "version": "2.31.0"},
            {"name": "cryptography", "version": "41.0.3"},
        ]
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            report = sv.build_report(packages)
        summary = report["summary"]
        assert summary["total"] == len(packages), "Packages must not be empty"
        assert summary["verified"] == len(report["verified"]), "Collection must not be empty"
        assert summary["unverified"] == len(report["unverified"]), "Collection must not be empty"
        assert summary["errors"] == len(report["errors"]), "Collection must not be empty"

    def test_empty_package_list_returns_zeroes(self) -> None:
        """build_report with no packages returns all-zero summary."""
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            report = sv.build_report([])
        assert report["summary"]["total"] == 0, "rep is not valid"
        assert report["summary"]["verified"] == 0, "rep is not valid"
        assert report["summary"]["unverified"] == 0, "rep is not valid"
        assert report["summary"]["errors"] == 0, "Error should be raised or set"


# ---------------------------------------------------------------------------
# Test 6: main() — CLI integration
# ---------------------------------------------------------------------------


class TestMainCLI:
    """Integration tests for the main() entry point."""

    def test_exit_0_when_no_mismatches(self, tmp_path: Path) -> None:
        """main() returns 0 when there are no signature mismatches."""
        lock = _make_lock_txt(tmp_path, "requests==2.31.0\n")
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            rc = sv.main(["--requirements", str(lock)])
        assert rc == 0, "rc is not valid"

    def test_exit_2_on_missing_file(self, tmp_path: Path) -> None:
        """main() returns 2 when the requirements file does not exist."""
        rc = sv.main(["--requirements", str(tmp_path / "nonexistent.txt")])
        assert rc == 2, "rc is not valid"

    def test_output_written_to_file(self, tmp_path: Path) -> None:
        """main() writes valid JSON to the --output path."""
        lock = _make_lock_txt(tmp_path, "urllib3==2.0.7\n")
        out = tmp_path / "report.json"
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            rc = sv.main(["--requirements", str(lock), "--output", str(out)])
        assert rc == 0, "rc is not valid"
        assert out.exists(), "Condition must be true"
        data = json.loads(out.read_text())
        assert "summary" in data, "Data must not be empty"

    def test_critical_only_flag_filters_packages(self, tmp_path: Path) -> None:
        """--critical-only only checks packages in CRITICAL_PACKAGES."""
        lock = _make_lock_txt(
            tmp_path,
            "requests==2.31.0\n" "some-random-lib==1.0.0\n",
        )
        out = tmp_path / "report.json"
        with patch.object(sv, "_SIGSTORE_AVAILABLE", False):
            sv.main(["--requirements", str(lock), "--critical-only", "--output", str(out)])
        data = json.loads(out.read_text())
        checked_names = {p["name"] for p in data["verified"] + data["unverified"] + data["errors"]}
        # some-random-lib is not in CRITICAL_PACKAGES → should be excluded
        assert "some-random-lib" not in checked_names, "Condition must be true"
        # requests IS in CRITICAL_PACKAGES → should be included
        assert "requests" in checked_names, "Condition must be true"

    def test_exit_1_on_critical_mismatch(self, tmp_path: Path) -> None:
        """main() returns 1 when a critical package has a signature mismatch."""
        lock = _make_lock_txt(tmp_path, "cryptography==41.0.3\n")
        mismatch_result = sv.VerificationResult(
            "cryptography", "41.0.3", "mismatch", "Tampered bundle"
        )
        with (
            patch.object(sv, "_SIGSTORE_AVAILABLE", True),
            patch.object(sv, "verify_package", return_value=mismatch_result),
        ):
            rc = sv.main(["--requirements", str(lock)])
        assert rc == 1, "rc is not valid"

    def test_exit_0_on_non_critical_mismatch(self, tmp_path: Path) -> None:
        """main() returns 0 (with warning) when mismatch is on a non-critical package."""
        lock = _make_lock_txt(tmp_path, "some-random-lib==1.0.0\n")
        mismatch_result = sv.VerificationResult(
            "some-random-lib", "1.0.0", "mismatch", "Tampered bundle"
        )
        with (
            patch.object(sv, "_SIGSTORE_AVAILABLE", True),
            patch.object(sv, "verify_package", return_value=mismatch_result),
        ):
            rc = sv.main(["--requirements", str(lock)])
        assert rc == 0, "rc is not valid"
