"""
Wiki Generator for Audit Pipeline v1.5.x

Generates GitHub Wiki-ready markdown files and creates a zip bundle
for easy deployment to the repository wiki.
"""

from __future__ import annotations

import json
import zipfile
from datetime import datetime
from pathlib import Path

__all__ = ["generate_wiki", "create_wiki_bundle", "WIKI_PAGES"]


# Wiki page definitions
WIKI_PAGES = {
    "Home": """# 🏠 {repo_name} Wiki

> **Audit Pipeline v{version}** | **Last Updated:** {timestamp}

Welcome to the {repo_name} documentation wiki! This wiki provides comprehensive documentation for the repository, including guides, API references, and architectural overviews.

## 🚀 Quick Navigation

| Section | Description |
|---------|-------------|
| [[Getting-Started]] | Quick start guide for new users |
| [[Audit-Pipeline]] | Audit Pipeline v1.5.x documentation |
| [[API-Reference]] | Complete API documentation |
| [[CLI-Commands]] | Command-line interface reference |
| [[Architecture]] | System architecture and diagrams |
| [[FAQ]] | Frequently asked questions |
| [[Troubleshooting]] | Common issues and solutions |

## 📊 System Overview

```mermaid
flowchart TB
    subgraph Core["🔍 Audit Pipeline v1.5.x"]
        AR[audit_runner.py] --> TD[(TrendDatabase)]
        AR --> TC[Comparison Engine]
        AR --> VIZ[Visualization]
    end
    
    subgraph Outputs["📤 Outputs"]
        Dashboard[HTML Dashboard]
        Reports[Trend Reports]
        Wiki[Wiki Docs]
    end
    
    VIZ --> Dashboard
    TC --> Reports
    Core --> Wiki
```

## 📋 Version History

| Version | Release | Highlights |
|---------|---------|------------|
| v1.5.5 | Dec 2024 | Pre-2.0 stabilization, performance tools |
| v1.5.4 | Dec 2024 | Webhooks, CI integration |
| v1.5.3 | Dec 2024 | Dashboard & reports |
| v1.5.2 | Dec 2024 | Visualization core |
| v1.5.1 | Dec 2024 | Historical comparison |
| v1.5.0 | Dec 2024 | Trend database foundation |

## 🔗 External Links

- [GitHub Repository](https://github.com/{repo_name})
- [Issue Tracker](https://github.com/{repo_name}/issues)
- [Pull Requests](https://github.com/{repo_name}/pulls)

---

*Generated by Audit Pipeline v{version}*
""",

    "Getting-Started": """# 🚀 Getting Started

> Quick start guide for {repo_name}

## Prerequisites

- Python 3.9+
- Git
- pip or uv package manager

## Installation

### 1. Clone the Repository

```bash
git clone https://github.com/{repo_name}.git
cd {repo_name}
```

### 2. Create Virtual Environment

```bash
python -m venv .venv
source .venv/bin/activate  # Linux/macOS
# or
.venv\\Scripts\\activate  # Windows
```

### 3. Install Dependencies

```bash
# Development installation
pip install -e .

# With optional ML dependencies
pip install -e .[ml]

# Development tools
pip install -r requirements-dev.txt
```

## Quick Commands

### Run Audit

```bash
python -m scripts.space_traversal.audit_runner run
```

### Check Regressions

```bash
python -m scripts.space_traversal.audit_runner check-regressions
```

### Generate Dashboard

```bash
python -m scripts.space_traversal.audit_runner dashboard
```

### View Capability Trend

```bash
python -m scripts.space_traversal.audit_runner show-trend checkpointing
```

## Configuration

Enable trend tracking in `.copilot-space/workflow.yaml`:

```yaml
trends:
  enabled: true
  database_path: "audit_artifacts/trends.db"
  auto_store: true
  retention:
    max_runs: 1000
    max_age_days: 365
```

## Next Steps

- [[Audit-Pipeline]] - Learn about the audit pipeline
- [[CLI-Commands]] - Explore all CLI commands
- [[API-Reference]] - Dive into the API

---

*See [[Home]] for navigation*
""",

    "Audit-Pipeline": """# 🔍 Audit Pipeline v1.5.x

> Comprehensive audit pipeline with trend tracking, visualization, and CI integration

## Overview

The Audit Pipeline v1.5.x series introduces systematic trend aggregation, historical comparison, and visualization capabilities.

```mermaid
flowchart LR
    subgraph Input
        Audit[Audit Run]
        Config[Configuration]
    end
    
    subgraph Processing
        Runner[audit_runner.py]
        DB[(TrendDatabase)]
        Compare[Comparison]
    end
    
    subgraph Output
        Dashboard[Dashboard]
        Reports[Reports]
        Alerts[Webhooks]
    end
    
    Audit --> Runner
    Config --> Runner
    Runner --> DB
    Runner --> Compare
    DB --> Dashboard
    Compare --> Reports
    Runner --> Alerts
```

## Release Versions

### v1.5.0 — Trend Database Foundation

| Component | Description |
|-----------|-------------|
| `TrendDatabase` | SQLite-based trend storage |
| `AuditSnapshot` | Audit run metadata dataclass |
| Schema migrations | Version-tracked migrations |

### v1.5.1 — Historical Comparison

| Component | Description |
|-----------|-------------|
| `ComparisonResult` | Detailed comparison results |
| Regression detection | Automated regression alerts |
| Severity classification | High/Medium/Low severity |

### v1.5.2 — Visualization Core

| Component | Description |
|-----------|-------------|
| `sparkline()` | Unicode trend visualization |
| `bar_chart()` | Horizontal bar charts |
| `generate_dashboard()` | Interactive HTML dashboard |

### v1.5.3 — Dashboard & Reports

| Component | Description |
|-----------|-------------|
| Jinja2 templates | Enhanced report templates |
| Executive summary | Trend arrows and metrics |
| Component analysis | Per-component breakdown |

### v1.5.4 — API & Hooks

| Component | Description |
|-----------|-------------|
| Webhooks | Slack, Teams, generic |
| CI Integration | GitHub, GitLab, Jenkins |
| HMAC signing | Secure webhook delivery |

### v1.5.5 — Pre-2.0 Stabilization

| Component | Description |
|-----------|-------------|
| Performance tools | Caching, profiling |
| Documentation | Wiki, API docs |
| Migration prep | v2.0 federation ready |

## Usage Examples

### Store Audit Snapshot

```python
from scripts.space_traversal.trend_db import TrendDatabase, create_snapshot_from_artifacts
from pathlib import Path

db = TrendDatabase("audit_artifacts/trends.db")
snapshot = create_snapshot_from_artifacts(Path("audit_artifacts"))
run_id = db.store_snapshot(snapshot)
print(f"Stored: {{run_id}}")
```

### Check Regressions

```python
regressions = db.get_regressions(threshold=0.02, lookback_runs=5)
for reg in regressions:
    print(f"{{reg['capability_id']}}: {{reg['delta']:.3f}} ({{reg['severity']}})")
```

### Generate Visualization

```python
from scripts.space_traversal.viz_ascii import sparkline, score_badge
from scripts.space_traversal.viz_html import generate_dashboard

# ASCII
trend = db.get_trend("checkpointing", limit=20)
scores = [t["score"] for t in reversed(trend)]
print(sparkline(scores))

# HTML Dashboard
generate_dashboard(capabilities, trend_data, Path("dashboard.html"))
```

---

*See [[API-Reference]] for complete API documentation*
""",

    "API-Reference": """# 📖 API Reference

> Complete API documentation for Audit Pipeline v1.5.x

## Modules Overview

```mermaid
graph TD
    subgraph Core
        TD[trend_db.py]
        TC[trend_compare.py]
        AR[audit_runner.py]
    end
    
    subgraph Visualization
        VA[viz_ascii.py]
        VH[viz_html.py]
        VCB[viz_cli_builder.py]
        VAC[viz_api_collection.py]
        VS[viz_swagger.py]
    end
    
    subgraph Integration
        WH[webhooks.py]
        CI[ci_integration.py]
        PF[performance.py]
    end
    
    AR --> TD
    AR --> TC
    AR --> VA
    AR --> VH
    AR --> WH
    AR --> CI
```

## trend_db.py

### Classes

#### `AuditSnapshot`

Dataclass representing a single audit run.

```python
@dataclass
class AuditSnapshot:
    run_id: str                    # UUID or timestamp-based ID
    timestamp: float               # Unix epoch
    repo_root_sha: str             # Repository state hash
    git_commit: Optional[str]      # Git commit SHA
    git_branch: Optional[str]      # Git branch name
    version: str                   # Pipeline version
    capabilities: dict[str, float] # {{capability_id: score}}
    components: dict[str, dict]    # {{capability_id: {{component: value}}}}
    weights: dict[str, float]      # Weights used
    coverage_stats: Optional[dict] # Coverage augmentation stats
    manifest_sha: str              # Manifest hash for integrity
```

#### `TrendDatabase`

SQLite-based trend storage.

```python
class TrendDatabase:
    def __init__(self, db_path: Path | str = "audit_artifacts/trends.db")
    def store_snapshot(self, snapshot: AuditSnapshot) -> str
    def get_trend(self, capability_id: str, limit: int = 30, branch: Optional[str] = None) -> list[dict]
    def get_latest_scores(self) -> dict[str, float]
    def get_regressions(self, threshold: float = 0.02, lookback_runs: int = 5) -> list[dict]
    def export_csv(self, output_path: Path, capability_id: Optional[str] = None) -> None
```

### Functions

#### `create_snapshot_from_artifacts`

```python
def create_snapshot_from_artifacts(
    artifacts_dir: Path,
    git_commit: Optional[str] = None,
    git_branch: Optional[str] = None,
) -> AuditSnapshot
```

## trend_compare.py

### Classes

#### `ComparisonResult`

```python
@dataclass
class ComparisonResult:
    capability_id: str
    old_score: float
    new_score: float
    delta: float
    old_components: dict[str, float]
    new_components: dict[str, float]
    component_deltas: dict[str, float]
    is_regression: bool
    regression_severity: Optional[str]
```

### Functions

#### `compare_runs`

```python
def compare_runs(
    old_path: Path,
    new_path: Path,
    threshold: float = 0.02,
) -> list[ComparisonResult]
```

## viz_ascii.py

### Functions

| Function | Description |
|----------|-------------|
| `sparkline(values, width)` | Unicode trend visualization |
| `bar_chart(data, width, show_values)` | Horizontal bar chart |
| `trend_indicator(current, previous, threshold)` | Emoji indicator |
| `score_badge(score)` | Color-coded badge |
| `capability_dashboard(...)` | Full terminal dashboard |

## viz_html.py

### Functions

| Function | Description |
|----------|-------------|
| `generate_dashboard(...)` | Interactive HTML dashboard |

## webhooks.py

### Classes

#### `AuditEvent`

```python
@dataclass
class AuditEvent:
    event_type: str      # "audit_complete", "regression_detected", etc.
    repo_name: str
    timestamp: float
    avg_score: float
    capability_count: int
    regression_count: int
    details: dict
```

### Functions

| Function | Description |
|----------|-------------|
| `send_webhook(url, event, secret, timeout)` | Generic webhook |
| `send_slack_notification(url, event)` | Slack message |
| `send_teams_notification(url, event)` | Teams card |

## ci_integration.py

### Functions

| Function | Description |
|----------|-------------|
| `detect_ci_environment()` | Auto-detect CI system |
| `write_github_step_summary(...)` | GitHub Actions summary |
| `set_github_output(name, value)` | Set output variable |
| `generate_pr_comment(...)` | PR comment markdown |

---

*See [[CLI-Commands]] for command-line usage*
""",

    "CLI-Commands": """# ⌨️ CLI Commands

> Complete CLI reference for Audit Pipeline v1.5.x

## Main Commands

### `audit run`

Execute a full audit run.

```bash
python -m scripts.space_traversal.audit_runner run [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--artifacts-dir` | Output directory for artifacts |
| `--config` | Configuration file path |
| `--verbose` | Enable verbose output |

### `store-trend`

Store current audit results in the trend database.

```bash
python -m scripts.space_traversal.audit_runner store-trend [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--artifacts-dir` | Artifacts directory path |
| `--db-path` | Database file path |

### `show-trend`

Display trend for a specific capability.

```bash
python -m scripts.space_traversal.audit_runner show-trend CAPABILITY [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--limit` | Number of runs to show (default: 20) |
| `--branch` | Filter by git branch |
| `--format` | Output format (table, json, csv) |

### `check-regressions`

Check for score regressions.

```bash
python -m scripts.space_traversal.audit_runner check-regressions [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--threshold` | Regression threshold (default: 0.02) |
| `--lookback` | Number of runs to compare (default: 5) |
| `--fail-on-high` | Exit with error on high severity |

### `compare-runs`

Compare two audit runs.

```bash
python -m scripts.space_traversal.audit_runner compare-runs [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--old` | Path to old audit results |
| `--new` | Path to new audit results |
| `--output` | Output report path |

### `dashboard`

Generate HTML dashboard.

```bash
python -m scripts.space_traversal.audit_runner dashboard [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--output` | Output HTML file path |
| `--title` | Dashboard title |

### `cli-builder`

Generate interactive CLI builder HTML.

```bash
python -m scripts.space_traversal.audit_runner cli-builder [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--output` | Output HTML file path |

### `api-collection`

Generate API collection HTML.

```bash
python -m scripts.space_traversal.audit_runner api-collection [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--output` | Output HTML file path |

### `api-docs`

Generate Swagger/OpenAPI documentation.

```bash
python -m scripts.space_traversal.audit_runner api-docs [OPTIONS]
```

| Option | Description |
|--------|-------------|
| `--output` | Output HTML file path |

## Usage Examples

### Full Audit Workflow

```bash
# Run audit
python -m scripts.space_traversal.audit_runner run

# Store in trend database
python -m scripts.space_traversal.audit_runner store-trend

# Check for regressions
python -m scripts.space_traversal.audit_runner check-regressions --fail-on-high

# Generate dashboard
python -m scripts.space_traversal.audit_runner dashboard --output dashboard.html
```

### Trend Analysis

```bash
# View trend for specific capability
python -m scripts.space_traversal.audit_runner show-trend checkpointing --limit 30

# Compare with baseline
python -m scripts.space_traversal.audit_runner compare-runs \\
    --old audit_artifacts/baseline.json \\
    --new audit_artifacts/capabilities_scored.json
```

---

*See [[API-Reference]] for programmatic usage*
""",

    "Architecture": """# 🏗️ Architecture

> System architecture and design documentation

## High-Level Architecture

```mermaid
flowchart TB
    subgraph Input["📥 Input Layer"]
        Repo[Repository Code]
        Config[Configuration]
        Baseline[Baseline Scores]
    end
    
    subgraph Core["🔍 Audit Core"]
        Scanner[Code Scanner]
        Scorer[Capability Scorer]
        Comparator[Comparator]
    end
    
    subgraph Storage["💾 Storage Layer"]
        DB[(Trend Database)]
        Artifacts[Audit Artifacts]
        Cache[File Cache]
    end
    
    subgraph Output["📤 Output Layer"]
        Dashboard[HTML Dashboard]
        Reports[Markdown Reports]
        Webhooks[Notifications]
        CI[CI Integration]
    end
    
    Repo --> Scanner
    Config --> Scanner
    Scanner --> Scorer
    Baseline --> Comparator
    Scorer --> Comparator
    Scorer --> DB
    Comparator --> Reports
    DB --> Dashboard
    Comparator --> Webhooks
    Scanner --> CI
```

## Component Architecture

### Audit Runner

The central orchestrator that coordinates all audit operations.

```mermaid
graph TD
    AR[audit_runner.py]
    
    subgraph Commands
        Run[run]
        Store[store-trend]
        Show[show-trend]
        Check[check-regressions]
        Compare[compare-runs]
        Dash[dashboard]
    end
    
    AR --> Run
    AR --> Store
    AR --> Show
    AR --> Check
    AR --> Compare
    AR --> Dash
```

### Trend Database

SQLite-based storage with schema migrations.

```mermaid
erDiagram
    audit_runs ||--o{{ capability_scores : contains
    audit_runs {{
        text run_id PK
        real timestamp
        text repo_root_sha
        text git_commit
        text git_branch
        text version
        text weights_json
        text coverage_stats_json
        text manifest_sha
    }}
    capability_scores {{
        int id PK
        text run_id FK
        text capability_id
        real score
        real functionality
        real consistency
        real tests
        real safeguards
        real documentation
    }}
```

### Visualization Pipeline

```mermaid
flowchart LR
    Data[Trend Data]
    
    subgraph ASCII["Terminal"]
        Spark[Sparklines]
        Bars[Bar Charts]
        Badges[Score Badges]
    end
    
    subgraph HTML["Web"]
        Dashboard[Dashboard]
        Charts[Chart.js]
        Tables[Data Tables]
    end
    
    Data --> Spark
    Data --> Bars
    Data --> Badges
    Data --> Dashboard
    Dashboard --> Charts
    Dashboard --> Tables
```

## Data Flow

### Audit Execution Flow

```mermaid
sequenceDiagram
    participant User
    participant Runner as audit_runner
    participant Scanner
    participant Scorer
    participant DB as TrendDatabase
    
    User->>Runner: audit run
    Runner->>Scanner: scan_repository()
    Scanner-->>Runner: findings
    Runner->>Scorer: score_capabilities()
    Scorer-->>Runner: scores
    Runner->>DB: store_snapshot()
    DB-->>Runner: run_id
    Runner-->>User: audit complete
```

### Regression Detection Flow

```mermaid
sequenceDiagram
    participant User
    participant Runner as audit_runner
    participant DB as TrendDatabase
    participant Compare as Comparator
    participant Webhook
    
    User->>Runner: check-regressions
    Runner->>DB: get_trend(all)
    DB-->>Runner: historical data
    Runner->>Compare: detect_regressions()
    Compare-->>Runner: regressions[]
    
    alt Regressions Found
        Runner->>Webhook: send_notification()
        Webhook-->>Runner: delivery status
    end
    
    Runner-->>User: regression report
```

## Deployment Architecture

### Local Development

```
├── audit_runner.py          # CLI entry point
├── trend_db.py              # Database layer
├── trend_compare.py         # Comparison logic
├── viz_*.py                 # Visualization modules
├── webhooks.py              # Notification system
├── ci_integration.py        # CI/CD helpers
└── performance.py           # Performance utilities
```

### CI/CD Integration

```mermaid
flowchart LR
    subgraph CI["CI Pipeline"]
        Build[Build]
        Test[Test]
        Audit[Audit]
    end
    
    subgraph Integration
        Summary[Step Summary]
        Output[Output Variables]
        Comment[PR Comment]
    end
    
    Build --> Test
    Test --> Audit
    Audit --> Summary
    Audit --> Output
    Audit --> Comment
```

---

*See [[API-Reference]] for implementation details*
""",

    "FAQ": """# ❓ Frequently Asked Questions

> Common questions about Audit Pipeline v1.5.x

## General

### What is the Audit Pipeline?

The Audit Pipeline is a systematic capability assessment tool that tracks, compares, and visualizes repository health metrics over time.

### What versions are available?

| Version | Status | Key Features |
|---------|--------|--------------|
| v1.4.0 | Stable | Core audit functionality |
| v1.5.x | Current | Trend tracking, visualization |
| v2.0.0 | Planned | Multi-repo federation |

### How do I enable trend tracking?

Add to `.copilot-space/workflow.yaml`:

```yaml
trends:
  enabled: true
  database_path: "audit_artifacts/trends.db"
  auto_store: true
```

## Installation

### What are the system requirements?

- Python 3.9 or higher
- SQLite 3.x (included with Python)
- 50MB disk space for trend database

### How do I install optional dependencies?

```bash
# ML dependencies
pip install -e .[ml]

# All optional dependencies
pip install -e .[all]
```

## Usage

### How do I run an audit?

```bash
python -m scripts.space_traversal.audit_runner run
```

### How do I check for regressions?

```bash
python -m scripts.space_traversal.audit_runner check-regressions
```

### How do I generate a dashboard?

```bash
python -m scripts.space_traversal.audit_runner dashboard --output dashboard.html
```

### How do I view trends for a capability?

```bash
python -m scripts.space_traversal.audit_runner show-trend checkpointing --limit 30
```

## Configuration

### What is the regression threshold?

Default is 0.02 (2%). A capability is considered regressed if its score drops by more than this amount compared to the average of recent runs.

### How do I configure webhooks?

```yaml
webhooks:
  slack:
    url: "https://hooks.slack.com/services/..."
    on_regression: true
    on_complete: false
```

### How do I customize the dashboard?

Pass options to the dashboard command:

```bash
python -m scripts.space_traversal.audit_runner dashboard \\
    --output custom_dashboard.html \\
    --title "My Custom Dashboard"
```

## Troubleshooting

### The database is locked

SQLite databases can lock if multiple processes access them simultaneously. Ensure only one audit process runs at a time.

### Regressions are not being detected

1. Check that trend tracking is enabled
2. Verify sufficient historical data exists (minimum 2 runs)
3. Review the regression threshold setting

### Dashboard is not loading

1. Check that all dependencies are installed
2. Verify the output path is writable
3. Check browser console for JavaScript errors

---

*See [[Troubleshooting]] for more detailed solutions*
""",

    "Troubleshooting": """# 🔧 Troubleshooting

> Common issues and solutions

## Database Issues

### SQLite Lock Error

**Symptom:** `database is locked` error

**Solution:**
```bash
# Kill any hanging processes
pkill -f audit_runner

# Check for lock file
ls -la audit_artifacts/*.db-*

# If lock persists, restart from clean state
rm audit_artifacts/trends.db-*
```

### Schema Migration Failed

**Symptom:** `schema version mismatch` error

**Solution:**
```python
from scripts.space_traversal.migrations import run_migrations
from pathlib import Path

# Run pending migrations
applied = run_migrations(Path("audit_artifacts/trends.db"))
print(f"Applied migrations: {{applied}}")
```

## Visualization Issues

### Dashboard Not Rendering

**Symptom:** Blank or broken dashboard

**Causes & Solutions:**

1. **Missing Chart.js CDN**
   - Check internet connectivity
   - Dashboard requires Chart.js from CDN

2. **Data format error**
   - Verify capabilities_scored.json exists
   - Check JSON syntax

3. **Browser compatibility**
   - Use modern browser (Chrome, Firefox, Safari)
   - Check console for JavaScript errors

### Sparklines Display Incorrectly

**Symptom:** Unicode characters not rendering

**Solution:**
```bash
# Ensure terminal supports Unicode
export LANG=en_US.UTF-8

# Or use ASCII fallback
python -m scripts.space_traversal.audit_runner show-trend checkpointing --ascii
```

## CI Integration Issues

### GitHub Step Summary Not Appearing

**Symptom:** Step summary missing in Actions

**Causes & Solutions:**

1. **Not running in GitHub Actions**
   - `GITHUB_STEP_SUMMARY` env var must be set
   - Only works in GitHub Actions environment

2. **Permission denied**
   - Check workflow permissions
   - Ensure `write` permission for `actions`

### Webhook Delivery Failed

**Symptom:** Notifications not arriving

**Causes & Solutions:**

1. **Invalid URL**
   ```python
   # Verify URL is accessible
   import urllib.request
   urllib.request.urlopen("https://hooks.slack.com/...", timeout=10)
   ```

2. **HMAC signature mismatch**
   - Verify secret matches on both ends
   - Check for encoding issues

3. **Network/firewall**
   - Check outbound connectivity
   - Verify webhook endpoint is accessible

## Performance Issues

### Audit Running Slowly

**Symptom:** Audit takes too long

**Solutions:**

1. **Enable file caching**
   ```python
   from scripts.space_traversal.performance import FileCache
   cache = FileCache(Path(".cache"))
   ```

2. **Use batch file reading**
   ```python
   from scripts.space_traversal.performance import batch_file_read
   contents = batch_file_read(file_paths, max_size=200_000)
   ```

3. **Profile slow stages**
   ```python
   from scripts.space_traversal.performance import profile_stage
   with profile_stage("scanning"):
       # slow operation
   ```

### Memory Usage High

**Symptom:** Out of memory during audit

**Solutions:**

1. **Process files in batches**
2. **Increase batch file read limit**
3. **Clear cache between runs**

## Import Errors

### Module Not Found

**Symptom:** `ModuleNotFoundError`

**Solution:**
```bash
# Ensure package is installed
pip install -e .

# Or add to PYTHONPATH
export PYTHONPATH="${{PYTHONPATH}}:$(pwd)"
```

### Optional Dependency Missing

**Symptom:** `ImportError` for ML libraries

**Solution:**
```bash
# Install ML extras
pip install -e .[ml]

# Or install specific package
pip install torch transformers
```

## Getting Help

If issues persist:

1. Check [[FAQ]] for common questions
2. Review [[Architecture]] for system understanding
3. File an issue on GitHub with:
   - Error message
   - Steps to reproduce
   - Environment details

---

*See [[Home]] for navigation*
""",

    "_Sidebar": """### Navigation

* [[Home]]
* [[Getting-Started]]

### Documentation

* [[Audit-Pipeline]]
* [[API-Reference]]
* [[CLI-Commands]]
* [[Architecture]]

### Help

* [[FAQ]]
* [[Troubleshooting]]

---

**v{version}** | [GitHub](https://github.com/{repo_name})
""",

    "_Footer": """---
*Generated by Audit Pipeline v{version}* | *{timestamp}* | [View on GitHub](https://github.com/{repo_name})
"""
}


def generate_wiki(
    output_dir: Path,
    repo_name: str = "Repository",
    version: str = "1.5.5",
) -> list[Path]:
    """
    Generate GitHub Wiki markdown files.

    Args:
        output_dir: Directory to write wiki files
        repo_name: Repository name for display
        version: Pipeline version

    Returns:
        List of generated file paths
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    generated_files = []

    for page_name, template in WIKI_PAGES.items():
        content = template.format(
            repo_name=repo_name,
            version=version,
            timestamp=timestamp,
        )

        file_path = output_dir / f"{page_name}.md"
        file_path.write_text(content, encoding="utf-8")
        generated_files.append(file_path)

    return generated_files


def create_wiki_bundle(
    output_dir: Path,
    bundle_path: Path,
    repo_name: str = "Repository",
    version: str = "1.5.5",
) -> Path:
    """
    Generate wiki files and create a zip bundle for deployment.

    Args:
        output_dir: Directory to write wiki files
        bundle_path: Path for the output zip file
        repo_name: Repository name
        version: Pipeline version

    Returns:
        Path to the created zip bundle
    """
    # Generate wiki files
    generated_files = generate_wiki(output_dir, repo_name, version)

    # Create manifest
    manifest = {
        "version": version,
        "repo_name": repo_name,
        "generated": datetime.now().isoformat(),
        "pages": [f.name for f in generated_files],
        "deployment_instructions": [
            "1. Clone your wiki repository: git clone https://github.com/{repo}.wiki.git",
            "2. Extract this bundle into the wiki directory",
            "3. Commit and push: git add . && git commit -m 'Update wiki' && git push",
        ],
    }

    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    generated_files.append(manifest_path)

    # Create zip bundle
    bundle_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(bundle_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file_path in generated_files:
            zf.write(file_path, file_path.name)

    return bundle_path


if __name__ == "__main__":
    import sys

    output = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("wiki")
    bundle = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("wiki_bundle.zip")
    repo = sys.argv[3] if len(sys.argv) > 3 else "Aries-Serpent/_codex_"

    bundle_path = create_wiki_bundle(output, bundle, repo)
    print(f"Generated wiki files in: {output}")
    print(f"Created bundle: {bundle_path}")
