- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      k8s-app: kubelet
    name: kubernetes-kubelet
    namespace: kube-system
  spec:
    endpoints:
    - interval: 60s
      port: https-metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __meta_kubernetes_node_name
        targetLabel: node
      scrapeTimeout: 30s
    selector:
      matchLabels:
        k8s-app: kubelet
