openapi: 3.0.3
info:
  title: Internal Tools API (ITA) — Bridge Skeleton
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /kb/search:
    post:
      summary: Search internal knowledge base
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [query, top_k]
              properties:
                query:
                  type: string
                top_k:
                  type: integer
                  minimum: 1
                  maximum: 20
                  default: 5
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title: { type: string }
                        url: { type: string }
                        snippet: { type: string }
  /repo/hygiene:
    post:
      summary: Lint/format/scan a diff (stub)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                diff: { type: string }
                checks:
                  type: array
                  items: { type: string }
      responses:
        "200":
          description: Hygiene report
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  findings:
                    type: array
                    items:
                      type: object
                      properties:
                        type: { type: string }
                        message: { type: string }
  /tests/run:
    post:
      summary: Run focused tests (stub)
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                pattern: { type: string }
      responses:
        "200":
          description: Test summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  passed: { type: integer }
                  failed: { type: integer }
                  duration_s: { type: number }
  /git/create-pr:
    post:
      summary: Create a pull request (dry-run default)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, body, head, base]
              properties:
                title: { type: string }
                body: { type: string }
                head: { type: string }
                base: { type: string }
                confirm:
                  type: boolean
                  description: Set true to actually proceed; default dry-run
      responses:
        "200":
          description: PR creation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  dry_run: { type: boolean }
                  message: { type: string }
                  pr_url: { type: string, nullable: true }
