minimum_pre_commit_version: "3.7.0"
default_install_hook_types: [pre-commit, pre-push, prepare-commit-msg]
exclude: '^\.codex/'

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff         # lint + import sort via rule I (configured in pyproject)
        args: ["--fix"]  # scope comes from pyproject.toml (e.g., select = ["E","F","I"])
      - id: ruff-format  # Black-compatible formatter
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args: ["-r","requirements.txt","--progress-spinner=off","--timeout","15"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: codex-block-large-generated
        name: Block large generated files in .codex
        entry: python tools/precommit_block_large.py
        language: system
        pass_filenames: true
