repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff         # lint + import sort via rule I (configured in pyproject)
        args: ["--fix"]  # scope comes from pyproject.toml (e.g., select = ["E","F","I"])
      - id: ruff-format  # Black-compatible formatter
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args: ["-r","requirements.txt","--progress-spinner=off","--timeout","15"]
