# BEGIN: CODEX_COMPOSE
version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: codex-api:local
    user: "10001:10001"
    ports:
      - '8000:8000'
    environment:
      - UVICORN_WORKERS=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - artifacts:/artifacts
    healthcheck:
      test: ['CMD', 'curl', '-fsS', 'http://localhost:8000/status']
      interval: 10s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  artifacts:
    name: codex_artifacts
