stages:
  prepare:
    cmd: python -m hhg_logistics.data.prepare "${params.paths.raw_input}" "${params.paths.prepared_dir}"
    deps:
      - src/hhg_logistics/data/prepare.py
      - "${params.paths.raw_input}"
    params:
      - prepare.seed
      - prepare.split
      - paths.raw_input
      - paths.prepared_dir
    outs:
      - "${params.paths.prepared_dir}"
