stages:
  prepare:
    cmd: python -m hhg_logistics.data.prepare "${params.paths.raw_input}" "${params.paths.prepared_dir}"
    deps:
      - src/hhg_logistics/data/prepare.py
      - "${params.paths.raw_input}"
    params:
      - prepare.seed
      - prepare.split
      - paths.raw_input
      - paths.prepared_dir
    outs:
      - "${paths.prepared_dir}"
  train_baseline:
    cmd: python -m hhg_logistics.train train.enable=true
    deps:
      - src/hhg_logistics/train.py
      - src/hhg_logistics/model/peft_utils.py
      - src/hhg_logistics/model/adapters.py
      - "${data.processed_dir}/features.csv"
    outs:
      - "${data.models_dir}"
