# PEP 621: Project metadata in pyproject.toml
# https://peps.python.org/pep-0621/
[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "codex-ml"
version = "0.1.0"
description = "Production-grade ML training/eval utilities for Codex workflows."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "Apache-2.0" }
authors = [{ name = "Codex Authors" }]
keywords = ["ml", "nlp", "training", "evaluation", "codex"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]

# Keep deps minimal; repo-specific pins still live in requirements*.txt if present.
dependencies = [
  "numpy>=1.23",
  "torch; platform_system != 'Windows'",        # avoid accidental CPU-only wheels bloat
  "transformers>=4.38",
  "datasets>=2.14",
  "tqdm>=4.64",
  "pyyaml>=6.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
  "pytest-cov>=4.0",
  "ruff>=0.5",
  "mypy>=1.6",
  "nox>=2024.3.2",
]
tokenizer = [
  "sentencepiece>=0.1.99",
]
train = [
  "torch>=2.1",
  "transformers>=4.38",
  "mlflow>=2.11",
  "peft>=0.11",
]

[project.urls]
Homepage = "https://github.com/Aries-Serpent/_codex_"
Issues = "https://github.com/Aries-Serpent/_codex_/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]           # src/ layout for reliable imports in tests/ and tooling
include = ["codex_ml*"]
namespaces = false

# Keep tooling blocks minimal; repo may already have dedicated config files.
[tool.ruff]
target-version = "py310"
line-length = 100

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
ignore_errors = true


[[tool.mypy.overrides]]
module = ["codex_ml.*"]
ignore_errors = true


[[tool.mypy.overrides]]
module = ["codex_ml.pipeline"]
ignore_errors = true
