"""Type stub for sentencepiece optional dependency stub"""
from typing import Any, Optional

class SentencePieceProcessor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def Load(self, *args: Any, **kwargs: Any) -> Any: ...
    def load(self, *args: Any, **kwargs: Any) -> Any: ...
    def EncodeAsIds(self, text: str) -> list[int]: ...
    def DecodeIds(self, ids: list[int]) -> str: ...
    def GetPieceSize(self) -> int: ...
    def PieceToId(self, piece: str) -> int: ...
    def IdToPiece(self, id: int) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def _load_real_module() -> Optional[Any]: ...
def __getattr__(name: str) -> Any: ...
