[metadata]
name = codex
version = 0.0.1

[options]
packages = find:
python_requires = >=3.10

[options.entry_points]
console_scripts =
    codex-eval = codex_ml.evaluation.cli:app

[mutmut]
also_copy =
    coverage_tests
    src/security/__init__.py
    src/security/providers
paths_to_mutate =
    src/security/provider_factory.py
    src/security/providers/aws_provider.py
pytest_add_cli_args =
    --noconftest
pytest_add_cli_args_test_selection =
    coverage_tests/test_security_providers_unittest.py
