name: Release
on:
  workflow_dispatch:
jobs:
  _codex_guard:
    if: false

  build-and-# push:  # disabled by Codex
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        # push:  # disabled by Codex true
        tags: ghcr.io/${{ github.repository }}:latest
    if: ${{ false }}
