# Auto-generated by codex_logging_workflow.py
import uuid
from codex.logging.session_logger import log_event, fetch_messages

def test_user_and_assistant_logged_roundtrip(tmp_path, monkeypatch):
    sid = f"pytest-{uuid.uuid4()}"
    log_event(sid, "user", "hello")
    log_event(sid, "assistant", "world")
    msgs = fetch_messages(sid)
    roles = [m["role"] for m in msgs]
    assert roles == ["user", "assistant"]
    assert msgs[0]["message"] == "hello"
    assert msgs[1]["message"] == "world"
