#!/usr/bin/env python3
"""
Update maturity documentation from AST analysis.
Compares current codebase against baseline to detect regressions.
"""
import json
import sys
from datetime import datetime
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

try:
    from codex.ast import CodeSmellDetector, parse_python
except ImportError:
    print("⚠️ codex.ast not available - skipping analysis")
    sys.exit(0)


def main():
    """Update maturity documentation based on AST analysis."""
    print("🔍 Running AST analysis for maturity update...")

    # Initialize components
    detector = CodeSmellDetector()

    # Analyze current state
    current_files = {}
    total_smells = 0
    error_smells = 0

    src_dir = Path("src")
    if not src_dir.exists():
        print("⚠️ src/ directory not found")
        sys.exit(0)

    for py_file in src_dir.rglob("*.py"):
        try:
            tree = parse_python(str(py_file))
            if tree:
                smells = detector.detect(tree)

                total_smells += len(smells)
                error_smells += sum(
                    1
                    for s in smells
                    if getattr(getattr(s, "severity", None), "name", None) == "ERROR"
                )

                current_files[str(py_file)] = {
                    "node_count": len(tree.children) if tree.children else 0,
                    "smells": len(smells),
                }
        except Exception as e:
            print(f"⚠️ Failed to analyze {py_file}: {e}")

    # Update maturity document
    maturity_doc = Path("docs/maturity/MATURITY_REMAINING_WORK.md")
    maturity_doc.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""# Maturity Remaining Work

Last Updated: {timestamp}

## AST Analysis Summary

- **Total Files Analyzed**: {len(current_files)}
- **Total Code Smells**: {total_smells}
- **Error-Level Smells**: {error_smells}

## Quality Metrics

{'✅ No critical issues detected' if error_smells == 0 else f'❌ {error_smells} error-level issues found'}

## Next Steps

1. Address error-level code smells
2. Review files with high smell counts
3. Continue improving code quality

---
*Generated by AST analysis system at {timestamp}*
"""

    maturity_doc.write_text(content)
    print(f"✅ Updated {maturity_doc}")

    # Exit with error if critical issues found
    if error_smells > 0:
        print(f"\n❌ Found {error_smells} error-level issues")
        sys.exit(1)

    print("\n✅ Maturity check passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
