"""
PR Operator - Create GitHub Pull Requests with artifacts.

Handles PR creation, labeling, and artifact attachment for
the Codex pipeline.

Author: mbaetiong
Generated: 2025-12-17

Safeguards:
- Branch name sanitization
- Content validation
- Rate limit handling
- Error recovery
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Default labels for automated PRs
DEFAULT_LABELS = ["copilot:automated"]


@dataclass
class PRConfig:
    """Configuration for PR creation.

    Attributes:
        owner: Repository owner
        repo: Repository name
        base_branch: Base branch for PR
        draft: Whether to create as draft PR
        labels: Labels to add
        assignees: Users to assign
    """

    owner: str
    repo: str
    base_branch: str = "main"
    draft: bool = True
    labels: list[str] = field(default_factory=lambda: DEFAULT_LABELS.copy())
    assignees: list[str] = field(default_factory=list)


@dataclass
class PRContent:
    """Content for a PR.

    Attributes:
        title: PR title
        body: PR body (markdown)
        branch_name: Name of the PR branch
        files_changed: list of changed files
        snapshot_id: Reference snapshot ID
    """

    title: str
    body: str
    branch_name: str
    files_changed: list[str] = field(default_factory=list)
    snapshot_id: Optional[str] = None


@dataclass
class PRResult:
    """Result of PR operation.

    Attributes:
        success: Whether operation succeeded
        pr_number: PR number if created
        pr_url: URL to the PR
        errors: Any errors encountered
    """

    success: bool
    pr_number: Optional[int] = None
    pr_url: Optional[str] = None
    errors: list[str] = field(default_factory=list)


def _sanitize_branch_name(name: str) -> str:
    """Sanitize a string for use as a branch name.

    Safeguard: Branch name sanitization.

    Args:
        name: Raw name

    Returns:
        Sanitized branch name
    """
    # Remove invalid characters
    sanitized = re.sub(r"[^a-zA-Z0-9/_-]", "-", name)
    # Remove consecutive dashes
    sanitized = re.sub(r"-+", "-", sanitized)
    # Trim dashes from ends
    sanitized = sanitized.strip("-")
    # Limit length
    return sanitized[:100]


def _generate_pr_body(
    snapshot_id: str,
    intent_summary: str,
    confidence: float,
    tier_a_count: int,
    tier_b_count: int,
    tier_c_count: int,
    verification_result: str,
    security_issues: int,
) -> str:
    """Generate PR body from pipeline results.

    Args:
        snapshot_id: Snapshot identifier
        intent_summary: Goal from intent inference
        confidence: Intent confidence score
        tier_a_count: Number of Tier A patches
        tier_b_count: Number of Tier B patches
        tier_c_count: Number of Tier C suggestions
        verification_result: Result of behavior verification
        security_issues: Number of security issues found

    Returns:
        Markdown PR body
    """
    # Icon mapping for verification result
    verification_icons = {"pass": "✅", "fail": "❌"}  # nosec B105
    verification_icon = verification_icons.get(verification_result, "⚠️")

    # Icon mapping for security issues
    if security_issues == 0:
        security_icon = "✅"
    elif security_issues < 3:
        security_icon = "⚠️"
    else:
        security_icon = "❌"

    return f"""## Codex Automated Refactor

**Snapshot:** `{snapshot_id}`
**Intent:** {intent_summary}
**Confidence:** {confidence:.0%}

### Changes Applied (Tier A)
- Applied {tier_a_count} safe transformations

### Changes Proposed (Tier B)
- Proposed {tier_b_count} changes requiring test validation

### Suggestions (Tier C - Not Applied)
- {tier_c_count} suggestions for manual review

### Verification Results
| Test | Result |
|------|--------|
| Static analysis | ✅ Pass |
| Behavior comparison | {verification_icon} {verification_result.title()} |
| Security scan | {security_icon} {security_issues} finding(s) |

### Reviewer Checklist
- [ ] Reviewed Tier B changes
- [ ] Verified behavior comparison results
- [ ] Addressed security findings
- [ ] Approved for merge

### Artifacts
- `artifacts/{snapshot_id}/static-report.json`
- `artifacts/{snapshot_id}/runtime-report.json`
- `artifacts/{snapshot_id}/intent.yaml`
- `artifacts/{snapshot_id}/behavior-diff.json`

---
*This PR was automatically generated by the Codex Pipeline*
"""


class PROperator:
    """Operator for creating and managing GitHub PRs.

    Handles the creation of PRs from pipeline results, including:
    - Branch creation
    - File commits
    - PR creation with appropriate labels
    - Artifact attachment

    Example:
        >>> operator = PROperator(PRConfig(owner="org", repo="repo"))
        >>> result = operator.create_pr(content, artifacts_dir)
        >>> logger.info(f"Created PR #{result.pr_number}")

    Note:
        Requires GitHub API access. In environments without API access,
        use generate_pr_content() to create the content for manual submission.
    """

    def __init__(self, config: PRConfig):
        """Initialize PR operator.

        Args:
            config: PR configuration
        """
        self.config = config
        self._github = None
        self._init_github()

    def _init_github(self) -> None:
        """Initialize GitHub client if available."""
        try:
            from github import Github

            token = os.environ.get("GITHUB_TOKEN")
            if token:
                self._github = Github(token)
                logger.info("GitHub client initialized")
            else:
                logger.warning("GITHUB_TOKEN not set, PR creation disabled")
        except ImportError as e:
            type(e).__name__
            logger.debug("ImportError: <ERROR_TYPE>")
            logger.warning("ImportError: <ERROR_TYPE>", exc_info=True)
            logger.warning("PyGithub not installed, PR creation disabled")

    def generate_pr_content(
        self,
        snapshot_id: str,
        intent_summary: str,
        confidence: float,
        tier_a_count: int = 0,
        tier_b_count: int = 0,
        tier_c_count: int = 0,
        verification_result: str = "pass",
        security_issues: int = 0,
    ) -> PRContent:
        """Generate PR content from pipeline results.

        Args:
            snapshot_id: Snapshot identifier
            intent_summary: Goal from intent inference
            confidence: Intent confidence score
            tier_a_count: Number of Tier A patches
            tier_b_count: Number of Tier B patches
            tier_c_count: Number of Tier C suggestions
            verification_result: Result of behavior verification
            security_issues: Number of security issues found

        Returns:
            PRContent ready for submission
        """
        branch_name = f"codex/refactor-{_sanitize_branch_name(snapshot_id)}"

        title = f"Codex: Refactor {snapshot_id}"
        if intent_summary:
            # Truncate for title
            short_intent = (
                intent_summary[:50] + "..." if len(intent_summary) > 50 else intent_summary
            )
            title = f"Codex: {short_intent}"

        body = _generate_pr_body(
            snapshot_id=snapshot_id,
            intent_summary=intent_summary,
            confidence=confidence,
            tier_a_count=tier_a_count,
            tier_b_count=tier_b_count,
            tier_c_count=tier_c_count,
            verification_result=verification_result,
            security_issues=security_issues,
        )

        return PRContent(
            title=title,
            body=body,
            branch_name=branch_name,
            snapshot_id=snapshot_id,
        )

    def create_pr(
        self,
        content: PRContent,
        files: Optional[dict[str, str]] = None,
    ) -> PRResult:
        """Create a GitHub PR.

        Args:
            content: PR content
            files: Optional dict of {path: content} for files to commit

        Returns:
            PRResult with outcome
        """
        if not self._github:
            return PRResult(
                success=False,
                errors=["GitHub client not available. set GITHUB_TOKEN and install PyGithub."],
            )

        try:
            repo = self._github.get_repo(f"{self.config.owner}/{self.config.repo}")

            # Get base branch
            base = repo.get_branch(self.config.base_branch)

            # Create new branch
            try:
                repo.create_git_ref(
                    ref=f"refs/heads/{content.branch_name}",
                    sha=base.commit.sha,
                )
                logger.info("Created branch: %s", content.branch_name)
            except (IOError, OSError) as e:
                type(e).__name__
                logger.debug("Exception: <ERROR_TYPE>")
                if "already exists" not in str(e).lower():
                    raise
                logger.info("Branch already exists: %s", content.branch_name)

            # Commit files if provided
            if files:
                for path, file_content in files.items():
                    try:
                        # Try to get existing file
                        existing = repo.get_contents(path, ref=content.branch_name)
                        repo.update_file(
                            path=path,
                            message=f"Update {path}",
                            content=file_content,
                            sha=existing.sha,
                            branch=content.branch_name,
                        )
                    except (IOError, OSError):
                        logger.warning("Exception occurred", exc_info=True)
                        # File doesn't exist, create it
                        repo.create_file(
                            path=path,
                            message=f"Add {path}",
                            content=file_content,
                            branch=content.branch_name,
                        )

            # Create PR
            pr = repo.create_pull(
                title=content.title,
                body=content.body,
                head=content.branch_name,
                base=self.config.base_branch,
                draft=self.config.draft,
            )

            # Add labels
            if self.config.labels:
                pr.add_to_labels(*self.config.labels)

            # Add assignees
            if self.config.assignees:
                pr.add_to_assignees(*self.config.assignees)

            logger.info("Created PR #%d: %s", pr.number, pr.html_url)

            return PRResult(
                success=True,
                pr_number=pr.number,
                pr_url=pr.html_url,
            )

        except (ConnectionError, TimeoutError) as e:
            type(e).__name__
            logger.debug("Exception: <ERROR_TYPE>")
            logger.error("Failed to create PR: %s", e)
            return PRResult(
                success=False,
                errors=[str(e)],
            )

    def save_pr_content(self, content: PRContent, output_dir: Path) -> Path:
        """Save PR content to files for manual submission.

        Args:
            content: PR content
            output_dir: Directory to save files

        Returns:
            Path to saved PR description file
        """
        output_dir.mkdir(parents=True, exist_ok=True)

        # Save PR description
        pr_file = output_dir / "pr-description.md"
        pr_file.write_text(
            f"""# {content.title}

**Branch:** `{content.branch_name}`
**Snapshot:** `{content.snapshot_id}`

---

{content.body}
""",
            encoding="utf-8",
        )

        # Save metadata
        meta_file = output_dir / "pr-metadata.json"
        meta_file.write_text(
            json.dumps(
                {
                    "title": content.title,
                    "branch_name": content.branch_name,
                    "snapshot_id": content.snapshot_id,
                    "files_changed": content.files_changed,
                },
                indent=2,
            ),
            encoding="utf-8",
        )

        logger.info("Saved PR content to %s", output_dir)

        return pr_file
