#!/usr/bin/env python3
"""PyO3 Integration Tester"""
import click
import re
from pathlib import Path
from typing import List, Dict

class PyO3Parser:
    def parse_rust_file(self, filepath: Path) -> List[Dict]:
        """Extract PyO3 bindings from Rust file"""
        bindings = []
        try:
            content = filepath.read_text()
            # Find #[pyfunction] declarations
            pyfunction_pattern = r'#\[pyfunction\]\s*(?:pub\s+)?fn\s+(\w+)\s*\([^)]*\)\s*(?:->\s*PyResult<([^>]+)>|->([^{]+))?'
            for match in re.finditer(pyfunction_pattern, content):
                func_name = match.group(1)
                return_type = match.group(2) or match.group(3) or 'None'
                bindings.append({
                    'type': 'function',
                    'name': func_name,
                    'return_type': return_type.strip(),
                    'file': str(filepath)
                })
        except Exception as e:
            click.echo(f"Error parsing {filepath}: {e}", err=True)
        return bindings
    
    def generate_test(self, binding: Dict) -> str:
        """Generate Python test code for a binding"""
        name = binding['name']
        
        # Validate name to prevent code injection
        # Only allow alphanumeric characters and underscores (valid Python identifiers)
        if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', name):
            raise ValueError(f"Invalid function name: {name}. Must be a valid Python identifier.")
        
        test_code = f'''# Auto-generated by pyo3-integration-tester
import pytest

def test_{name}_happy_path():
    """Test {name} happy path."""
    from codex_swarm import {name}
    # TODO: Add appropriate test data
    result = {name}()
    assert result is not None

def test_{name}_type_validation():
    """Test {name} type validation."""
    from codex_swarm import {name}
    # TODO: Add type validation tests
    pass
'''
        if 'PyResult' in binding.get('return_type', ''):
            test_code += f'''
def test_{name}_error_handling():
    """Test {name} error handling."""
    from codex_swarm import {name}
    with pytest.raises(Exception):
        # TODO: Add error case
        pass
'''
        return test_code

@click.group()
def cli():
    """PyO3 Integration Tester"""
    pass

@cli.command()
@click.option('--rust-dir', type=click.Path(exists=True), required=True)
@click.option('--output', type=click.Path(), default='tests/')
def generate(rust_dir, output):
    """Generate integration tests from Rust bindings"""
    parser = PyO3Parser()
    output_path = Path(output)
    output_path.mkdir(parents=True, exist_ok=True)
    
    all_bindings = []
    for rust_file in Path(rust_dir).rglob('*.rs'):
        bindings = parser.parse_rust_file(rust_file)
        all_bindings.extend(bindings)
    
    click.echo(f"Found {len(all_bindings)} PyO3 bindings")
    
    for binding in all_bindings:
        test_code = parser.generate_test(binding)
        test_file = output_path / f"test_{binding['name']}_integration.py"
        test_file.write_text(test_code)
        click.echo(f"Generated: {test_file}")
    
    click.echo(f"\nGenerated {len(all_bindings)} test files in {output}")

if __name__ == '__main__':
    cli()
