#!/usr/bin/env python3
"""
PyO3 Integration Tester Agent

Validates Python-Rust bindings and auto-generates comprehensive integration tests
for PyO3 functions, ensuring type safety, error handling, and performance.

Usage:
    python -m pyo3_integration_tester --rust-dir ./rust_src --output ./tests
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import click
import yaml


@dataclass
class Binding:
    """Represents a PyO3 binding discovered in Rust code."""
    type: str  # 'function' or 'class'
    name: str
    return_type: str
    parameters: list[dict]
    file: str
    line: int
    is_async: bool = False
    has_error_handling: bool = False


class TestGenerator:
    """Generates Python test code for PyO3 bindings."""

    def __init__(self, module_name: str = "codex_swarm"):
        self.module_name = module_name

    def _validate_identifier(self, name: str) -> None:
        """Validate that name is a safe Python identifier."""
        if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', name):
            raise ValueError(f"Invalid identifier: {name}")

    def generate_test(self, binding: Binding) -> str:
        """Generate Python test code for a binding."""
        self._validate_identifier(binding.name)

        test_code = f'''"""
Auto-generated integration tests for {binding.name}
Generated by: pyo3-integration-tester
Source: {binding.file}:{binding.line}
"""
import pytest


def test_{binding.name}_happy_path():
    """Test {binding.name} with valid inputs."""
    from {self.module_name} import {binding.name}

    # TODO: Add appropriate test data based on function signature
    # Function signature: {binding.return_type}
    result = {binding.name}()
    assert result is not None


def test_{binding.name}_type_validation():
    """Test {binding.name} with invalid types."""
    from {self.module_name} import {binding.name}

    # TODO: Add type validation tests
    # Expected types: {', '.join([p.get('type', 'Any') for p in binding.parameters])}
    pass
'''

        # Add error handling test if function returns PyResult
        if 'PyResult' in binding.return_type or binding.has_error_handling:
            test_code += f'''

def test_{binding.name}_error_handling():
    """Test {binding.name} error handling."""
    from {self.module_name} import {binding.name}

    with pytest.raises(Exception):
        # TODO: Add error case that should raise exception
        pass
'''

        # Add async test if function is async
        if binding.is_async:
            test_code += f'''

@pytest.mark.asyncio
async def test_{binding.name}_async():
    """Test {binding.name} async behavior."""
    from {self.module_name} import {binding.name}

    result = await {binding.name}()
    assert result is not None
'''

        # Add performance smoke test
        test_code += f'''

@pytest.mark.performance
def test_{binding.name}_performance():
    """Smoke test for {binding.name} performance."""
    import time
    from {self.module_name} import {binding.name}

    start = time.time()
    result = {binding.name}()
    duration = time.time() - start

    # Should complete within reasonable time (1 second)
    assert duration < 1.0, f"Function took {{duration:.2f}}s"
'''

        return test_code


class PyO3IntegrationTester:
    """
    Main agent for testing PyO3 Python-Rust bindings.

    Capabilities:
    - Parse Rust files for PyO3 bindings
    - Extract function signatures and metadata
    - Generate comprehensive Python tests
    - Validate binding safety and correctness
    """

    def __init__(self, config_path: Optional[Path] = None):
        """Initialize tester with optional config."""
        self.config = self._load_config(config_path)
        self.patterns = self._compile_patterns()
        self.discovered_bindings: list[Binding] = []

    def _load_config(self, config_path: Optional[Path]) -> dict:
        """Load tester configuration."""
        if config_path and config_path.exists():
            with open(config_path) as f:
                return yaml.safe_load(f)
        return self._default_config()

    def _default_config(self) -> dict:
        """Return default configuration."""
        return {
            'version': '1.0.0',
            'enabled': True,
            'module_name': 'codex_swarm',
            'test_types': {
                'happy_path': True,
                'type_validation': True,
                'error_handling': True,
                'performance': True,
                'async': True,
            },
            'performance_threshold_seconds': 1.0,
            'recursive_scan': True,
            'file_patterns': ['*.rs'],
        }

    def _compile_patterns(self) -> dict:
        """Compile regex patterns for detection."""
        return {
            'pyfunction': re.compile(
                r'#\[pyfunction(?:\([^)]*\))?\]\s*'
                r'(?:pub\s+)?'
                r'(?:async\s+)?'
                r'fn\s+(\w+)\s*'
                r'\(([^)]*)\)\s*'
                r'(?:->\s*(PyResult<[^>]+>|[^{]+))?',
                re.MULTILINE
            ),
            'pymethods': re.compile(
                r'#\[pymethods\]',
                re.MULTILINE
            ),
            'parameter': re.compile(
                r'(\w+)\s*:\s*([^,)]+)'
            ),
        }

    def parse_rust_file(self, filepath: Path) -> list[Binding]:
        """
        Parse a Rust file and extract PyO3 bindings.

        Args:
            filepath: Path to Rust source file

        Returns:
            List of Binding objects found in file
        """
        bindings = []

        try:
            content = filepath.read_text()
            content.splitlines()

            # Find all #[pyfunction] declarations
            for match in self.patterns['pyfunction'].finditer(content):
                func_name = match.group(1)
                params_str = match.group(2) or ""
                return_type = match.group(3) or "None"

                # Parse parameters
                parameters = []
                for param_match in self.patterns['parameter'].finditer(params_str):
                    param_name = param_match.group(1)
                    param_type = param_match.group(2).strip()
                    parameters.append({
                        'name': param_name,
                        'type': param_type
                    })

                # Determine line number
                line_num = content[:match.start()].count('\n') + 1

                # Check if async - look in the matched text itself
                matched_text = match.group(0)
                is_async = 'async' in matched_text or 'async' in content[max(0, match.start()-100):match.start()]

                # Check if has error handling (returns PyResult)
                has_error_handling = 'PyResult' in return_type

                binding = Binding(
                    type='function',
                    name=func_name,
                    return_type=return_type.strip(),
                    parameters=parameters,
                    file=str(filepath),
                    line=line_num,
                    is_async=is_async,
                    has_error_handling=has_error_handling
                )
                bindings.append(binding)

        except Exception as e:
            click.echo(f"Error parsing {filepath}: {e}", err=True)

        return bindings

    def scan_directory(self, directory: Path, recursive: bool = None) -> list[Binding]:
        """
        Scan a directory for Rust files and extract bindings.

        Args:
            directory: Directory to scan
            recursive: Override config for recursive scan

        Returns:
            List of all bindings found
        """
        if recursive is None:
            recursive = self.config['recursive_scan']

        all_bindings = []
        pattern = '**/*.rs' if recursive else '*.rs'

        for rust_file in directory.glob(pattern):
            bindings = self.parse_rust_file(rust_file)
            all_bindings.extend(bindings)

        self.discovered_bindings = all_bindings
        return all_bindings

    def generate_tests(
        self,
        bindings: list[Binding],
        output_dir: Path,
        overwrite: bool = False
    ) -> dict[str, Path]:
        """
        Generate test files for bindings.

        Args:
            bindings: List of bindings to generate tests for
            output_dir: Directory to write test files
            overwrite: Whether to overwrite existing files

        Returns:
            Dict mapping binding names to generated test file paths
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        generator = TestGenerator(self.config['module_name'])

        generated_files = {}

        for binding in bindings:
            test_code = generator.generate_test(binding)
            test_file = output_dir / f"test_{binding.name}_integration.py"

            if test_file.exists() and not overwrite:
                click.echo(f"Skipping existing: {test_file}")
                continue

            test_file.write_text(test_code)
            generated_files[binding.name] = test_file
            click.echo(f"Generated: {test_file}")

        return generated_files

    def generate_report(self, bindings: list[Binding]) -> dict:
        """
        Generate a summary report of discovered bindings.

        Args:
            bindings: List of bindings

        Returns:
            Dictionary with summary statistics
        """
        unique_files = set(b.file for b in bindings)
        async_count = sum(1 for b in bindings if b.is_async)
        error_handling_count = sum(1 for b in bindings if b.has_error_handling)

        return {
            'total_bindings': len(bindings),
            'unique_files': len(unique_files),
            'async_functions': async_count,
            'functions_with_error_handling': error_handling_count,
            'bindings_by_file': {
                file: sum(1 for b in bindings if b.file == file)
                for file in unique_files
            },
        }


@click.command()
@click.option('--rust-dir', type=click.Path(exists=True), required=True, help='Rust source directory')
@click.option('--output', type=click.Path(), default='tests/', help='Output directory for tests')
@click.option('--config', type=click.Path(exists=True), help='Config file path')
@click.option('--recursive/--no-recursive', default=True, help='Scan subdirectories')
@click.option('--overwrite', is_flag=True, help='Overwrite existing test files')
@click.option('--report', is_flag=True, help='Show summary report')
def main(rust_dir, output, config, recursive, overwrite, report):
    """PyO3 Integration Tester CLI"""
    tester = PyO3IntegrationTester(Path(config) if config else None)

    # Scan for bindings
    click.echo(f"Scanning {rust_dir} for PyO3 bindings...")
    bindings = tester.scan_directory(Path(rust_dir), recursive=recursive)
    click.echo(f"Found {len(bindings)} PyO3 bindings")

    # Generate tests
    if bindings:
        output_path = Path(output)
        generated = tester.generate_tests(bindings, output_path, overwrite=overwrite)
        click.echo(f"\nGenerated {len(generated)} test files in {output_path}")

    # Show report if requested
    if report:
        report_data = tester.generate_report(bindings)
        click.echo("\n=== Summary Report ===")
        click.echo(f"Total bindings: {report_data['total_bindings']}")
        click.echo(f"Files scanned: {report_data['unique_files']}")
        click.echo(f"Async functions: {report_data['async_functions']}")
        click.echo(f"With error handling: {report_data['functions_with_error_handling']}")


if __name__ == '__main__':
    main()
