#!/usr/bin/env python3
"""
_secrets_encryption_helper.py — Sodium encryption helpers for GitHub Secrets API.

Provides symmetric and asymmetric encryption utilities for:
- GitHub Actions Secrets (public key encryption)
- GitHub Dependabot Secrets (Dependabot public key)
- GitHub Codespaces Secrets (Codespaces public key)

Key design principles
---------------------
Public Key Encapsulation:
    Secrets are sealed using GitHub's public key via libsodium crypto_box.
    The public key is fetched from the appropriate GitHub API endpoint.
    Only GitHub has the private key to decrypt.

Error Handling:
    Validates public key format before encryption.
    Checks key size (32 bytes for Curve25519).
    Raises descriptive errors for missing or invalid keys.

Usage
-----
    from _secrets_encryption_helper import encrypt_secret, decrypt_secret_mock

    # Fetch and encrypt a secret for Actions
    encrypted = encrypt_secret(
        secret_value="my-secret-token",
        public_key=base64_encoded_key,
        key_type="actions"
    )

    # Use in GitHub API PUT request
    body = {
        "encrypted_value": encrypted["encrypted_value"],
        "key_id": encrypted["key_id"]
    }
"""

from __future__ import annotations

import base64
import hmac
import hashlib
import logging
from typing import Any

log = logging.getLogger(__name__)

# Try to import libsodium (sodium) for encryption
try:
    import nacl.public
    import nacl.utils
    SODIUM_AVAILABLE = True
except ImportError:
    SODIUM_AVAILABLE = False
    log.warning("libsodium not available; mock encryption will be used")


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

GITHUB_PUBLIC_KEY_SIZE = 32  # Curve25519 key size
API_VERSION = "2026-03-10"
ACCEPT = "application/vnd.github+json"


# ---------------------------------------------------------------------------
# Public Key Helpers
# ---------------------------------------------------------------------------


def validate_public_key(public_key_b64: str, key_type: str = "actions") -> dict[str, Any]:
    """
    Validate and decode a GitHub public key.

    Args:
        public_key_b64: Base64-encoded public key from GitHub API
        key_type: Type of key ('actions', 'dependabot', 'codespaces')

    Returns:
        Dict with decoded key and metadata

    Raises:
        ValueError: If key is invalid or malformed
    """
    try:
        decoded_key = base64.b64decode(public_key_b64)
    except Exception as err:
        raise ValueError(f"Invalid base64 encoding for {key_type} public key") from err

    if len(decoded_key) != GITHUB_PUBLIC_KEY_SIZE:
        raise ValueError(
            f"{key_type} public key must be {GITHUB_PUBLIC_KEY_SIZE} bytes, "
            f"got {len(decoded_key)}"
        )

    return {
        "decoded": decoded_key,
        "b64": public_key_b64,
        "key_type": key_type,
        "size": len(decoded_key),
    }


# ---------------------------------------------------------------------------
# Encryption
# ---------------------------------------------------------------------------


def encrypt_secret(
    secret_value: str,
    public_key: str,
    key_id: str | None = None,
    key_type: str = "actions",
) -> dict[str, str]:
    """
    Encrypt a secret using GitHub's public key.

    Uses libsodium crypto_box to seal the secret. The resulting ciphertext
    is base64-encoded for use in GitHub API PUT requests.

    Args:
        secret_value: The plaintext secret to encrypt
        public_key: Base64-encoded GitHub public key
        key_id: Key ID from GitHub (optional, for reference)
        key_type: Type of key ('actions', 'dependabot', 'codespaces')

    Returns:
        Dict with 'encrypted_value' (base64), 'key_id', and 'key_type'

    Raises:
        ValueError: If encryption fails or key is invalid
    """
    if not SODIUM_AVAILABLE:
        raise RuntimeError(
            "libsodium not available; install with: pip install PyNaCl"
        )

    # Validate and decode the public key
    key_info = validate_public_key(public_key, key_type)
    decoded_key = key_info["decoded"]

    try:
        # Import public key into nacl
        pk = nacl.public.PublicKey(decoded_key)

        # Encrypt the secret using crypto_box
        # The nonce is automatically generated by nacl
        box = nacl.public.SealedBox(pk)
        ciphertext = box.encrypt(secret_value.encode("utf-8"))

        # Return base64-encoded result
        return {
            "encrypted_value": base64.b64encode(ciphertext).decode("utf-8"),
            "key_id": key_id or "unknown",
            "key_type": key_type,
        }
    except Exception as err:
        raise ValueError(f"Failed to encrypt secret: {err}") from err


# ---------------------------------------------------------------------------
# HMAC Signature Validation (for webhook payloads)
# ---------------------------------------------------------------------------


def compute_webhook_signature(
    payload: bytes,
    secret: str,
    algorithm: str = "sha256",
) -> str:
    """
    Compute GitHub webhook payload signature (HMAC-SHA256).

    GitHub signs webhook payloads using HMAC-SHA256 with the webhook secret.
    The signature is returned as hex(X-Hub-Signature-256).

    Args:
        payload: Raw webhook payload bytes
        secret: Webhook secret (configured in GitHub webhook settings)
        algorithm: Hash algorithm ('sha256' default, 'sha1' legacy)

    Returns:
        Hex-encoded signature (e.g., "sha256=abc123...")
    """
    if algorithm == "sha256":
        hash_obj = hmac.new(
            secret.encode("utf-8"),
            payload,
            hashlib.sha256,
        )
    elif algorithm == "sha1":
        hash_obj = hmac.new(
            secret.encode("utf-8"),
            payload,
            hashlib.sha1,
        )
    else:
        raise ValueError(f"Unsupported algorithm: {algorithm}")

    return f"{algorithm}={hash_obj.hexdigest()}"


def validate_webhook_signature(
    payload: bytes,
    secret: str,
    signature_header: str,
    algorithm: str = "sha256",
) -> bool:
    """
    Validate a GitHub webhook payload signature.

    Compares the X-Hub-Signature-256 header against the computed HMAC.
    Uses constant-time comparison to prevent timing attacks.

    Args:
        payload: Raw webhook payload bytes
        secret: Webhook secret
        signature_header: X-Hub-Signature-256 header value
        algorithm: Hash algorithm to use

    Returns:
        True if signature is valid, False otherwise
    """
    computed = compute_webhook_signature(payload, secret, algorithm)

    # Use constant-time comparison
    return hmac.compare_digest(computed, signature_header)


# ---------------------------------------------------------------------------
# Mock Encryption (for testing without libsodium)
# ---------------------------------------------------------------------------


def encrypt_secret_mock(
    secret_value: str,
    public_key: str,
    key_id: str | None = None,
    key_type: str = "actions",
) -> dict[str, str]:
    """
    Mock encryption for testing when libsodium is not available.

    Uses base64 encoding instead of actual crypto_box.
    ONLY for testing — never use in production.

    Args:
        secret_value: The secret to "encrypt"
        public_key: Base64-encoded GitHub public key (validated for structure)
        key_id: Key ID
        key_type: Type of key

    Returns:
        Dict with 'encrypted_value' (base64-mock), 'key_id', 'key_type'
    """
    # Still validate the key structure
    validate_public_key(public_key, key_type)

    # Mock encryption: just base64-encode the secret with a marker
    mock_ciphertext = f"MOCK_ENCRYPTED:{secret_value}".encode("utf-8")
    return {
        "encrypted_value": base64.b64encode(mock_ciphertext).decode("utf-8"),
        "key_id": key_id or "mock_key_id",
        "key_type": key_type,
    }


# ---------------------------------------------------------------------------
# Secret Decryption (for validation only — GitHub decrypts on their side)
# ---------------------------------------------------------------------------


def decrypt_secret_mock(encrypted_value: str) -> str:
    """
    Mock decryption for testing purposes only.

    This is NOT how GitHub decrypts — they use their private key.
    This is only for test verification to ensure we encrypted correctly.

    Args:
        encrypted_value: Base64-encoded mock ciphertext

    Returns:
        Original secret value

    Raises:
        ValueError: If decryption fails or not a mock encrypted value
    """
    try:
        decoded = base64.b64decode(encrypted_value)
        text = decoded.decode("utf-8")
        if text.startswith("MOCK_ENCRYPTED:"):
            return text[len("MOCK_ENCRYPTED:") :]
        raise ValueError("Not a mock encrypted value")
    except Exception as err:
        raise ValueError(f"Failed to decrypt mock value: {err}") from err


def get_encryption_method() -> str:
    """Return the encryption method being used ('libsodium' or 'mock')."""
    return "libsodium" if SODIUM_AVAILABLE else "mock"
