#!/usr/bin/env python3
"""
scripts/ci/check_pr_comments.py
────────────────────────────────
Hardened PR Comment Review Gate (REQ-13 / S227)

Scans ALL comments on the active PR and classifies each as:
  - UNADDRESSED: comment from mbaetiong or any bot that has not received a
    reply from copilot-swe-agent[bot] or github-copilot[bot]
  - ADDRESSED: comment that has a subsequent reply from a Copilot agent
  - REVIEW_THREAD: unresolved PR review thread

Exit codes:
  0 — all high-priority comments addressed
  1 — unaddressed blocking comment from mbaetiong or critical bot
  2 — unaddressed warning-level comments (bot informational)
  3 — usage / API error

Usage:
  python scripts/ci/check_pr_comments.py --pr NUMBER --repo OWNER/REPO
  python scripts/ci/check_pr_comments.py --pr NUMBER --repo OWNER/REPO --output-json FILE
  python scripts/ci/check_pr_comments.py --pr NUMBER --repo OWNER/REPO --metrics-file metrics.prom
  python scripts/ci/check_pr_comments.py --pr NUMBER --repo OWNER/REPO --post-checklist

Environment:
  GITHUB_TOKEN or GH_TOKEN — required for API access
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from datetime import datetime, timezone
from typing import Any
from urllib import error, request

logger = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

# Authors whose unaddressed comments are BLOCKING (exit code 1)
BLOCKING_AUTHORS: set[str] = {"mbaetiong"}

# Bot authors whose unaddressed comments are BLOCKING when they are CI gates
BLOCKING_BOTS: set[str] = {
    "github-actions[bot]",
    "copilot-pull-request-reviewer[bot]",
    "github-advanced-security[bot]",
    "github-code-quality[bot]",
}

# Bot authors whose unaddressed comments are WARNING-level (exit code 2)
WARNING_BOTS: set[str] = {
    "dependabot[bot]",
    "codecov[bot]",
    "snyk-bot",
    "renovate[bot]",
}

# Authors who count as "Copilot responded"
COPILOT_AGENTS: set[str] = {
    "copilot-swe-agent[bot]",
    "github-copilot[bot]",
    "Copilot",
}

# Comments whose body starts with any of these HTML markers are self-referential
# gate outputs and must be exempt from the scan (prevents circular blocking).
SKIP_BODY_MARKERS: tuple[str, ...] = (
    "<!-- comment-review-gate-checklist -->",
    "<!-- comment-review-gate:",          # PR-scoped gate failure comment (new format)
    "<!-- ci-rescue:",
    "<!-- pre-merge-validation-summary -->",
    "<!-- auto-fix-ci-issues -->",
    "<!-- copilot-escalation:",
    "<!-- ci-rescue-rca:",
    "<!-- ci-rescue-deep:",
    "<!-- cognitive-preflight-checklist -->",
    "<!-- cognitive-preflight-session-directives -->",
    "<!-- PR_STATUS_DASHBOARD_v1 -->",
    "<!-- BRANCH_REBASE_RESOLVED -->",
    "<!-- agent-token-delegation-result -->",
    "<!-- root-org-validation-v1 -->",
    "<!-- cost-check-bot -->",
    "<!-- agent-file-size-gate -->",       # Agent File Size Gate failure comment
    "<!-- session-gate-queued -->",        # Session concurrency gate — operational, not actionable
    "<!-- self-healing-escalation -->",    # Iterative self-healing escalation (Phase 5+)
    "<!-- workflow-execution-gate:",       # WEC gate execution plan
    "<!-- session-requirements-pending -->",  # Session requirements file — injected into next prompt
    "<!-- pr-followup-prompt-generated -->",  # Follow-up prompt generated by pr-followup-generator.yml
    "<!-- compiled-bot-feedback",             # Compiled bot feedback (bare: <!-- compiled-bot-feedback --> or SHA-suffixed: <!-- compiled-bot-feedback:SHA -->)
    "<!-- session-done-retrigger -->",         # Session-done re-trigger comment (copilot-agent-session-done.yml)
    "<!-- session-done-loop-break -->",        # Session-done loop-break guard (copilot-agent-session-done.yml)
)

# Text-content patterns for comments that lack an HTML marker but are still
# self-referential / operational and should never block the gate.  These are
# checked against the first 80 chars of the comment body (after lstrip).
SKIP_TEXT_PATTERNS: tuple[str, ...] = (
    "## Self-Healing Escalation",   # Phase 5 iterative-self-healing-ci.yml escalation (no HTML marker)
    "## 🤖 Copilot Self-Healing Escalation",  # Phase 8 copilot-escalation fallback
)

GITHUB_API = "https://api.github.com"


# ── GitHub API helper ─────────────────────────────────────────────────────────

def gh_get(path: str, token: str) -> Any:
    url = f"{GITHUB_API}{path}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    req = request.Request(url, headers=headers)
    try:
        with request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")[:200]
        raise RuntimeError(f"HTTP {e.code} GET {path}: {body}") from e


def gh_get_all_pages(path: str, token: str) -> list[Any]:
    """Fetch all pages of a paginated endpoint."""
    results: list[Any] = []
    page = 1
    while True:
        sep = "&" if "?" in path else "?"
        data = gh_get(f"{path}{sep}per_page=100&page={page}", token)
        if not isinstance(data, list):
            # Some endpoints wrap in a dict
            if isinstance(data, dict) and "comments" in data:
                data = data["comments"]
            else:
                results.append(data)
                break
        if not data:
            break
        results.extend(data)
        if len(data) < 100:
            break
        page += 1
    return results


# ── Core logic ────────────────────────────────────────────────────────────────

def classify_comment(comment: dict[str, Any]) -> dict[str, Any]:
    """Return enriched comment record with classification metadata."""
    login: str = (comment.get("user") or {}).get("login", "unknown")
    user_type: str = (comment.get("user") or {}).get("type", "User")
    created_at: str = comment.get("created_at", "")
    body: str = (comment.get("body") or "")[:500]
    url: str = comment.get("html_url", "")
    comment_id: int = comment.get("id", 0)

    is_bot = login.endswith("[bot]") or user_type == "Bot"
    is_blocking_human = login in BLOCKING_AUTHORS
    is_blocking_bot = login in BLOCKING_BOTS
    is_warning_bot = login in WARNING_BOTS

    category: str
    if is_blocking_human:
        category = "blocking_human"
    elif is_blocking_bot:
        category = "blocking_bot"
    elif is_bot and is_warning_bot:
        category = "warning_bot"
    elif is_bot:
        category = "info_bot"
    else:
        category = "human"

    return {
        "id": comment_id,
        "author": login,
        "category": category,
        "created_at": created_at,
        "url": url,
        "body_preview": body[:120].replace("\n", " "),
        "addressed": False,  # will be updated below
    }


def find_unaddressed_comments(
    pr_number: int,
    repo: str,
    token: str,
) -> dict[str, Any]:
    """
    Fetch all PR comments and review comments, then determine which
    are unaddressed by a Copilot agent.

    Returns a report dict.
    """
    # 1. PR issue comments (general conversation)
    issue_comments = gh_get_all_pages(
        f"/repos/{repo}/issues/{pr_number}/comments", token
    )

    # 2. PR review comments (inline code review)
    review_comments = gh_get_all_pages(
        f"/repos/{repo}/pulls/{pr_number}/comments", token
    )

    # 3. PR reviews (review-level bodies)
    reviews = gh_get_all_pages(
        f"/repos/{repo}/pulls/{pr_number}/reviews", token
    )

    # 4. PR commits — used as an additional Copilot-response signal.
    # When a COPILOT_AGENTS member pushes a commit after a review comment,
    # that commit IS a response: it means the agent addressed the concern in
    # code.  Including commit timestamps here prevents review threads from
    # remaining "blocking" when the fix was already committed (S_PR3946).
    pr_commits = gh_get_all_pages(
        f"/repos/{repo}/pulls/{pr_number}/commits", token
    )

    # Build timeline of Copilot responses (by timestamp) from ALL comment sources
    # AND commits so that review-posted replies and code fixes are both captured.
    copilot_response_times: list[datetime] = []

    def _parse_ts(ts: str) -> datetime | None:
        """Parse an ISO-8601 timestamp, returning None on failure."""
        if not ts:
            return None
        try:
            return datetime.fromisoformat(ts.replace("Z", "+00:00"))
        except ValueError:
            print(
                f"[check_pr_comments] Warning: unparseable timestamp {ts!r} — skipping",
                file=sys.stderr,
            )
            return None

    for c in issue_comments:
        login = (c.get("user") or {}).get("login", "")
        if login in COPILOT_AGENTS:
            dt = _parse_ts(c.get("created_at", ""))
            if dt is not None:
                copilot_response_times.append(dt)

    for c in review_comments:
        login = (c.get("user") or {}).get("login", "")
        if login in COPILOT_AGENTS:
            dt = _parse_ts(c.get("created_at", ""))
            if dt is not None:
                copilot_response_times.append(dt)

    for r in reviews:
        login = (r.get("user") or {}).get("login", "")
        if login in COPILOT_AGENTS:
            dt = _parse_ts(r.get("submitted_at", ""))
            if dt is not None:
                copilot_response_times.append(dt)

    # Include commit timestamps from COPILOT_AGENTS as response signals.
    # A commit by a Copilot agent that lands AFTER a review comment means the
    # agent addressed that concern in code — the commit IS the response.
    for commit in pr_commits:
        # commit author: commit.author.login (may be absent) or commit.committer.login
        author_login = (
            (commit.get("author") or {}).get("login", "")
            or (commit.get("committer") or {}).get("login", "")
        )
        if author_login in COPILOT_AGENTS:
            # Use the committer date (when it landed) rather than author date
            commit_data = commit.get("commit", {})
            committer_ts = (commit_data.get("committer") or {}).get("date", "")
            author_ts = (commit_data.get("author") or {}).get("date", "")
            dt = _parse_ts(committer_ts or author_ts)
            if dt is not None:
                copilot_response_times.append(dt)

    # Build an explicit reply index from review_comments: comment_id -> [copilot reply times]
    # This uses GitHub's `in_reply_to_id` field so that direct thread replies are detected
    # without relying solely on a global timestamp heuristic.
    copilot_reply_index: dict[int, list[datetime]] = {}
    for c in review_comments:
        login = (c.get("user") or {}).get("login", "")
        if login in COPILOT_AGENTS:
            parent_id = c.get("in_reply_to_id")
            dt = _parse_ts(c.get("created_at", ""))
            if parent_id is not None and dt is not None:
                copilot_reply_index.setdefault(int(parent_id), []).append(dt)

    def first_copilot_response_after(comment_ts: datetime) -> datetime | None:
        """Return the earliest Copilot response timestamp strictly after *comment_ts*."""
        candidates = [rt for rt in copilot_response_times if rt > comment_ts]
        return min(candidates) if candidates else None

    def was_addressed(comment_ts_str: str, comment_id: int | None = None) -> tuple[bool, float | None]:
        """Return (addressed, latency_seconds).

        For review comments, first checks whether a Copilot agent posted a direct
        reply (matched via ``in_reply_to_id``).  Falls back to the global
        timestamp heuristic for all other comment types.

        Returns latency_seconds as the elapsed seconds from comment creation to
        the first Copilot reply, or None if not addressed / latency unknown.
        """
        if not comment_ts_str:
            return False, None
        comment_ts = _parse_ts(comment_ts_str)
        if comment_ts is None:
            return False, None

        # 1. Explicit reply check (review comments with in_reply_to_id)
        if comment_id is not None:
            direct_replies = copilot_reply_index.get(comment_id, [])
            if direct_replies:
                first_reply = min(direct_replies)
                latency = (first_reply - comment_ts).total_seconds()
                return True, max(latency, 0.0)

        # 2. Global timestamp heuristic fallback
        first_response = first_copilot_response_after(comment_ts)
        if first_response is not None:
            latency = (first_response - comment_ts).total_seconds()
            return True, max(latency, 0.0)

        return False, None

    # Classify all comments
    all_records: list[dict[str, Any]] = []

    for c in issue_comments:
        login = (c.get("user") or {}).get("login", "")
        if login in COPILOT_AGENTS:
            continue  # Copilot's own comments don't need addressing
        body_start = (c.get("body") or "")[:80]
        if any(body_start.lstrip().startswith(m) for m in SKIP_BODY_MARKERS):
            continue  # Self-referential gate output — exempt from scan
        if any(body_start.lstrip().startswith(p) for p in SKIP_TEXT_PATTERNS):
            continue  # Known operational text pattern — exempt from scan
        rec = classify_comment(c)
        rec["comment_type"] = "issue_comment"
        addressed_flag, latency = was_addressed(c.get("created_at", ""))
        rec["addressed"] = addressed_flag
        rec["response_latency_seconds"] = latency
        all_records.append(rec)

    for c in review_comments:
        login = (c.get("user") or {}).get("login", "")
        if login in COPILOT_AGENTS:
            continue
        # Skip review comments whose referenced diff location is no longer part
        # of the current patch. For REST `/pulls/{pr}/comments` payloads this is
        # represented by `position` becoming null while `original_position`
        # remains populated. Such comments are outdated and cannot be acted on
        # in the current diff, so they should not be treated as blocking.
        if c.get("position") is None and c.get("original_position") is not None:
            continue
        rec = classify_comment(c)
        rec["comment_type"] = "review_comment"
        addressed_flag, latency = was_addressed(
            c.get("created_at", ""), comment_id=c.get("id")
        )
        rec["addressed"] = addressed_flag
        rec["response_latency_seconds"] = latency
        all_records.append(rec)

    for r in reviews:
        login = (r.get("user") or {}).get("login", "")
        if login in COPILOT_AGENTS:
            continue
        body = (r.get("body") or "").strip()
        if not body:
            continue  # Skip empty review bodies
        # Apply same SKIP_BODY_MARKERS / SKIP_TEXT_PATTERNS checks as issue comments.
        body_start = body[:80]
        if any(body_start.lstrip().startswith(m) for m in SKIP_BODY_MARKERS):
            continue
        if any(body_start.lstrip().startswith(p) for p in SKIP_TEXT_PATTERNS):
            continue
        # COMMENTED reviews from blocking bots are informational overviews, not
        # change requests. Only CHANGES_REQUESTED state is blocking; APPROVED /
        # COMMENTED / DISMISSED are downgraded to info so they never stall CI.
        state = (r.get("state") or "").upper()
        rec = classify_comment(r)
        if rec["category"] == "blocking_bot" and state != "CHANGES_REQUESTED":
            rec["category"] = "info_bot"
        rec["comment_type"] = "review"
        addressed_flag, latency = was_addressed(r.get("submitted_at", ""))
        rec["addressed"] = addressed_flag
        rec["response_latency_seconds"] = latency
        all_records.append(rec)

    # Separate by category
    unaddressed_blocking: list[dict] = []
    unaddressed_warning: list[dict] = []
    unaddressed_info: list[dict] = []
    addressed: list[dict] = []

    for rec in all_records:
        if rec["addressed"]:
            addressed.append(rec)
            continue
        cat = rec["category"]
        if cat in ("blocking_human", "blocking_bot"):
            unaddressed_blocking.append(rec)
        elif cat == "warning_bot":
            unaddressed_warning.append(rec)
        else:
            unaddressed_info.append(rec)

    return {
        "pr_number": pr_number,
        "repo": repo,
        "scanned_at": datetime.now(timezone.utc).isoformat(),
        "total_comments": len(all_records),
        "addressed_count": len(addressed),
        "unaddressed_blocking": unaddressed_blocking,
        "unaddressed_warning": unaddressed_warning,
        "unaddressed_info": unaddressed_info,
        "addressed": addressed,
        "exit_code": (
            1 if unaddressed_blocking else
            2 if unaddressed_warning else
            0
        ),
    }


# ── Checklist poster ──────────────────────────────────────────────────────────

def build_checklist_body(report: dict[str, Any]) -> str:
    """Build the markdown checklist posted to the PR."""
    total = report["total_comments"]
    addressed = report["addressed_count"]
    blocking = report["unaddressed_blocking"]
    warning = report["unaddressed_warning"]
    info = report["unaddressed_info"]
    run_url = os.environ.get(
        "GITHUB_RUN_URL",
        f"https://github.com/{report['repo']}/actions"
    )

    lines = [
        "<!-- comment-review-gate-checklist -->",
        "## 🔍 PR Comment Review Gate — Copilot Must Address All Items",
        "",
        "> **Policy (§0 Codebase Agency Policy):** ALL comments from `mbaetiong` and ALL bot-posted comments MUST be reviewed and addressed before new work begins.",
        "",
        f"**Scan results:** {addressed}/{total} comments addressed · "
        f"Scanned at {report['scanned_at'][:16]} UTC",
        "",
    ]

    if not blocking and not warning and not info:
        lines += [
            "### ✅ All Comments Addressed",
            "",
            "No unaddressed comments found. You may proceed with new work.",
        ]
    else:
        if blocking:
            lines += [
                "### 🚨 BLOCKING — Must address before ANY new commits",
                "",
                "| # | Author | Type | Preview | Link |",
                "|---|--------|------|---------|------|",
            ]
            for i, c in enumerate(blocking, 1):
                author = c["author"]
                ctype = c["comment_type"].replace("_", " ")
                preview = c["body_preview"][:80].replace("|", "╎")
                url = c["url"]
                lines.append(
                    f"| {i} | `@{author}` | {ctype} | {preview} | [View]({url}) |"
                )
            lines += [
                "",
                "**Instructions:** Reply to each row above with your resolution before committing.",
                "",
            ]

        if warning:
            lines += [
                "### ⚠️ WARNINGS — Bot comments requiring review",
                "",
                "| # | Author | Type | Preview | Link |",
                "|---|--------|------|---------|------|",
            ]
            for i, c in enumerate(warning, 1):
                author = c["author"]
                ctype = c["comment_type"].replace("_", " ")
                preview = c["body_preview"][:80].replace("|", "╎")
                url = c["url"]
                lines.append(
                    f"| {i} | `@{author}` | {ctype} | {preview} | [View]({url}) |"
                )
            lines.append("")

        if info:
            lines += [
                "<details>",
                f"<summary>ℹ️ Informational comments ({len(info)}) — click to expand</summary>",
                "",
                "| # | Author | Type | Preview | Link |",
                "|---|--------|------|---------|------|",
            ]
            for i, c in enumerate(info, 1):
                author = c["author"]
                ctype = c["comment_type"].replace("_", " ")
                preview = c["body_preview"][:60].replace("|", "╎")
                url = c["url"]
                lines.append(
                    f"| {i} | `@{author}` | {ctype} | {preview} | [View]({url}) |"
                )
            lines += ["</details>", ""]

    lines += [
        "---",
        "",
        "**To dismiss this checklist:** Reply to every blocking item above, then push a new commit. The gate will re-scan on the next push.",
        "",
        f"_[🔗 Workflow run]({run_url})_",
    ]

    return "\n".join(lines)


def write_session_requirements(report: dict[str, Any], path: str) -> None:
    """Write unaddressed blocking comments as session requirements for the next Copilot prompt.

    The output file is injected at the beginning of the Copilot agent session prompt
    by the ``cognitive-preflight`` job in ``agent-auth-delegation.yml``.  This implements
    the "pre-pend to session prompt" contract from ``.codex/CODEBASE_AGENCY_POLICY.md §0a``:
    pending comments are surfaced as *session directives* rather than CI blockers.

    Output format:
        Markdown file starting with ``<!-- session-requirements-pending -->`` marker
        (which is in ``SKIP_BODY_MARKERS`` so the comment-review gate ignores it if
        the file is ever posted as a PR comment).  The body contains a table of every
        unaddressed blocking comment with author, preview, and a direct link.

    Retention:
        Uploaded as ``session-requirements-{PR}`` GitHub Actions artifact with 7-day
        retention by ``comment-review-gate.yml``.  The cognitive-preflight job in
        ``agent-auth-delegation.yml`` downloads this artifact and reads the file via
        ``fs.readFileSync`` before constructing the preflight checklist body.

    When ``--write-session-requirements`` is set the gate exits 0 even when blocking
    comments are present (non-blocking mode).  The normal exit-code-1 path is only
    used when the flag is absent.

    Args:
        report: Report dict returned by ``find_unaddressed_comments()``.
        path:   Filesystem path to write the markdown file to.
    """
    blocking = report["unaddressed_blocking"]
    warning = report["unaddressed_warning"]
    pr = report["pr_number"]
    scanned_at = report["scanned_at"][:16]

    lines = [
        "<!-- session-requirements-pending -->",
        "## 📋 Pending Comment Requirements — Pre-pended to Session Prompt",
        "",
        f"> **Auto-generated** by `comment-review-gate.yml` at {scanned_at} UTC",
        f"> PR #{pr} has {len(blocking)} unaddressed blocking comment(s).",
        "> These requirements are injected into the Copilot session prompt instead of blocking CI.",
        "",
    ]

    if blocking:
        lines += [
            "### 🚨 Must Address (Blocking — from `mbaetiong` or CI bots)",
            "",
            "| # | Author | Preview | Link |",
            "|---|--------|---------|------|",
        ]
        for i, c in enumerate(blocking, 1):
            author = c["author"]
            preview = c["body_preview"][:80].replace("|", "╎")
            url = c["url"]
            lines.append(f"| {i} | `@{author}` | {preview} | [View]({url}) |")
        lines += [
            "",
            "**Agent Instructions:** Reply to each blocking comment above with your",
            "resolution before pushing new commits. Use the GitHub API or `gh` CLI.",
            "",
        ]

    if warning:
        lines += [
            "### ⚠️ Review Required (Warning — bot comments)",
            "",
        ]
        for c in warning:
            lines.append(f"- `@{c['author']}`: {c['body_preview'][:80]} ([View]({c['url']}))")
        lines.append("")

    lines += [
        "---",
        f"_Generated by comment-review-gate.yml · PR #{pr} · {scanned_at} UTC_",
    ]

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Session requirements written to {path}")


def post_checklist(
    report: dict[str, Any],
    pr_number: int,
    repo: str,
    token: str,
) -> None:
    """Upsert the checklist comment on the PR."""
    MARKER = "<!-- comment-review-gate-checklist -->"
    body = build_checklist_body(report)

    # Get existing comments
    comments = gh_get_all_pages(
        f"/repos/{repo}/issues/{pr_number}/comments", token
    )
    existing = next(
        (c for c in comments if MARKER in (c.get("body") or "")), None
    )

    import json as _json
    payload = _json.dumps({"body": body}).encode()
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
    }

    if existing:
        url = f"{GITHUB_API}/repos/{repo}/issues/comments/{existing['id']}"
        req = request.Request(url, data=payload, headers=headers, method="PATCH")
        action = "Updated"
    else:
        url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
        req = request.Request(url, data=payload, headers=headers, method="POST")
        action = "Created"

    try:
        with request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read())
        print(f"{action} comment #{result.get('id')} on PR #{pr_number}")
    except error.HTTPError as e:
        body_err = e.read().decode("utf-8", errors="replace")[:200]
        raise RuntimeError(f"HTTP {e.code} posting checklist: {body_err}") from e


def write_prometheus_metrics(report: dict[str, Any], path: str) -> None:
    """Write Prometheus text-format metrics for comment-response latency.

    Emitted metric families:
      comment_review_gate_total           — total comments scanned
      comment_review_gate_addressed_total — comments with a Copilot response
      comment_review_gate_blocking_total  — unaddressed blocking comments (mbaetiong)
      comment_review_gate_warning_total   — unaddressed warning comments (bots)
      comment_review_gate_info_total      — unaddressed info comments
      comment_review_gate_response_latency_seconds — per-comment response latency
      comment_review_gate_exit_code       — exit code emitted by the gate run
    """
    pr = report["pr_number"]
    scanned_at = report.get("scanned_at", "")

    lines: list[str] = [
        "# HELP comment_review_gate_total Total comments scanned on the PR",
        "# TYPE comment_review_gate_total gauge",
        f'comment_review_gate_total{{pr="{pr}",repo="{report["repo"]}"}} {report["total_comments"]}',
        "",
        "# HELP comment_review_gate_addressed_total Comments that have a Copilot agent reply",
        "# TYPE comment_review_gate_addressed_total gauge",
        f'comment_review_gate_addressed_total{{pr="{pr}",repo="{report["repo"]}"}} {report["addressed_count"]}',
        "",
        "# HELP comment_review_gate_blocking_total Unaddressed BLOCKING comments (mbaetiong)",
        "# TYPE comment_review_gate_blocking_total gauge",
        f'comment_review_gate_blocking_total{{pr="{pr}",repo="{report["repo"]}"}} {len(report["unaddressed_blocking"])}',
        "",
        "# HELP comment_review_gate_warning_total Unaddressed WARNING comments (bots)",
        "# TYPE comment_review_gate_warning_total gauge",
        f'comment_review_gate_warning_total{{pr="{pr}",repo="{report["repo"]}"}} {len(report["unaddressed_warning"])}',
        "",
        "# HELP comment_review_gate_info_total Unaddressed INFO comments",
        "# TYPE comment_review_gate_info_total gauge",
        f'comment_review_gate_info_total{{pr="{pr}",repo="{report["repo"]}"}} {len(report["unaddressed_info"])}',
        "",
        "# HELP comment_review_gate_exit_code Exit code returned by this gate run (0=pass, 1=blocking, 2=warning)",
        "# TYPE comment_review_gate_exit_code gauge",
        f'comment_review_gate_exit_code{{pr="{pr}",repo="{report["repo"]}"}} {report["exit_code"]}',
        "",
    ]

    # Per-comment response latency (seconds from comment creation to first Copilot reply)
    # `response_latency_seconds` is populated by `was_addressed()` for every comment that
    # received a Copilot reply (addressed_flag=True, latency≥0).  It is None for unaddressed
    # comments.  For unaddressed blocking/warning comments we emit a separate
    # `comment_review_gate_pending_seconds` gauge (time still waiting since creation) so
    # the metric family is never dead even on first-session PRs with no Copilot replies yet.
    all_comments = (
        report["addressed"]
        + report["unaddressed_blocking"]
        + report["unaddressed_warning"]
        + report["unaddressed_info"]
    )
    latency_lines: list[str] = []
    pending_lines: list[str] = []
    try:
        now_utc = datetime.now(tz=timezone.utc)
    except Exception:
        now_utc = None
    for c in all_comments:
        latency_val = c.get("response_latency_seconds")
        author = c.get("author", "unknown")[:32]
        ctype = c.get("comment_type", "unknown")
        if latency_val is not None:
            latency_lines.append(
                f'comment_review_gate_response_latency_seconds{{pr="{pr}",'
                f'repo="{report["repo"]}",author="{author}",type="{ctype}"}} {latency_val:.3f}'
            )
        elif not c.get("addressed") and now_utc is not None:
            # Emit pending age for unaddressed comments so the gauge is never empty.
            created_str = c.get("created_at") or c.get("submitted_at") or ""
            try:
                created_ts = datetime.fromisoformat(created_str.replace("Z", "+00:00"))
                pending_secs = max((now_utc - created_ts).total_seconds(), 0.0)
                pending_lines.append(
                    f'comment_review_gate_pending_seconds{{pr="{pr}",'
                    f'repo="{report["repo"]}",author="{author}",type="{ctype}"}} {pending_secs:.3f}'
                )
            except (ValueError, TypeError):  # skip comments with unparseable timestamps
                logger.debug("Suppressed exception in handler", exc_info=True)
    if latency_lines:
        lines += [
            "# HELP comment_review_gate_response_latency_seconds Seconds from comment creation to first Copilot reply",
            "# TYPE comment_review_gate_response_latency_seconds gauge",
        ] + latency_lines + [""]

    if pending_lines:
        lines += [
            "# HELP comment_review_gate_pending_seconds Seconds an unaddressed comment has been waiting for a Copilot reply",
            "# TYPE comment_review_gate_pending_seconds gauge",
        ] + pending_lines + [""]

    # Timestamp comment (informational)
    lines += [f"# Scanned at {scanned_at} — repo={report['repo']} pr={pr}"]

    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Prometheus metrics written to {path}")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="PR Comment Review Gate — enforce that all mbaetiong/bot comments are addressed"
    )
    parser.add_argument("--pr", type=int, required=True, help="PR number")
    parser.add_argument("--repo", required=True, help="owner/repo")
    parser.add_argument("--output-json", metavar="FILE", help="Write JSON report to FILE")
    parser.add_argument("--metrics-file", metavar="FILE",
                        help="Write Prometheus text-format metrics to FILE")
    parser.add_argument("--post-checklist", action="store_true",
                        help="Post/update checklist comment on the PR")
    parser.add_argument("--write-session-requirements", metavar="FILE",
                        help=(
                            "Write unaddressed blocking comments as session requirements to FILE "
                            "for injection into the next Copilot session prompt. When specified, "
                            "the gate exits 0 even if blocking comments exist (non-blocking mode)."
                        ))
    parser.add_argument("--dry-run", action="store_true",
                        help="Print checklist body without posting")
    args = parser.parse_args()

    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN", "")
    if not token:
        print("ERROR: GH_TOKEN or GITHUB_TOKEN environment variable required", file=sys.stderr)
        return 3

    try:
        report = find_unaddressed_comments(args.pr, args.repo, token)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 3

    if args.output_json:
        with open(args.output_json, "w") as fh:
            json.dump(report, fh, indent=2)
        print(f"Report written to {args.output_json}")

    if args.metrics_file:
        write_prometheus_metrics(report, args.metrics_file)

    if args.write_session_requirements:
        write_session_requirements(report, args.write_session_requirements)

    # Print summary
    blocking = report["unaddressed_blocking"]
    warning = report["unaddressed_warning"]
    info = report["unaddressed_info"]
    total = report["total_comments"]
    addressed = report["addressed_count"]

    print(f"\nPR #{args.pr} comment scan — {report['repo']}")
    print(f"  Total comments   : {total}")
    print(f"  Addressed        : {addressed}")
    print(f"  Blocking unaddressed : {len(blocking)}")
    print(f"  Warning unaddressed  : {len(warning)}")
    print(f"  Info unaddressed     : {len(info)}")

    if blocking:
        print("\nBLOCKING — must address before proceeding:")
        for c in blocking:
            print(f"  [{c['category']}] @{c['author']} ({c['comment_type']}): {c['body_preview'][:80]}")
            print(f"    → {c['url']}")

    if warning:
        print("\nWARNING — bot comments requiring review:")
        for c in warning:
            print(f"  @{c['author']}: {c['body_preview'][:80]}")

    checklist_body = build_checklist_body(report)

    if args.dry_run:
        print("\n--- CHECKLIST BODY (dry-run) ---")
        print(checklist_body)
    elif args.post_checklist:
        post_checklist(report, args.pr, args.repo, token)

    # When --write-session-requirements is set, blocking comments are captured as
    # session directives injected into the next Copilot prompt.  The gate itself
    # exits 0 so CI stays green and the session can proceed.
    if args.write_session_requirements and report["exit_code"] == 1:
        print(
            "\nNOTE: Blocking comments exist but --write-session-requirements is set. "
            "Requirements written to file. Gate exits 0 (non-blocking mode)."
        )
        return 0

    return report["exit_code"]


if __name__ == "__main__":
    sys.exit(main())
