#!/usr/bin/env python3
"""
check_docs_index.py — Enforce INDEX.md presence in every docs/ subdirectory.

WHY THIS EXISTS
---------------
With 1,388+ markdown files across 125 subdirectories in docs/, important runbooks,
policies, and guides become invisible without a discoverable index in each directory.
Agents, CI workflows, and humans all rely on INDEX.md files to navigate the codebase
documentation. Missing indexes are a documentation debt that compounds over time.

This script provides the GROUNDED METHOD to ensure nothing is overlooked:
  - Run in pre-commit hooks: catches missing indexes before they're committed
  - Run in CI: gates PRs that add docs/ subdirectories without an index
  - Run by agents: verifies documentation completeness before session close
  - Run in scheduled audit: weekly report of documentation health

Usage
-----
    # Check all docs/ subdirectories (default):
    python scripts/ci/check_docs_index.py

    # Check a specific directory tree:
    python scripts/ci/check_docs_index.py --root docs/ops

    # Auto-generate stub INDEX.md files for missing ones (dry-run first):
    python scripts/ci/check_docs_index.py --generate --dry-run
    python scripts/ci/check_docs_index.py --generate

    # Only check directories with N or more .md files (skip tiny dirs):
    python scripts/ci/check_docs_index.py --min-files 3

    # Fail if missing indexes exist:
    python scripts/ci/check_docs_index.py --strict

Exit codes
----------
    0  All checked directories have an INDEX.md (or --strict not set and warnings only)
    1  One or more directories missing INDEX.md (in --strict mode)
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_ROOT = REPO_ROOT / "docs"

# Directories to skip entirely (no docs/ subdirs that need indexing)
SKIP_DIRS = {
    "assets", "stylesheets", "_layouts", "diffs", "diagrams",
    "demos", "for-human-removal",
}

# Filenames that count as an index
INDEX_NAMES = {"INDEX.md", "index.md", "README.md"}


def find_dirs_without_index(
    root: Path,
    min_files: int = 1,
) -> list[tuple[Path, int]]:
    """Return (directory, file_count) for each subdir missing an index."""
    missing: list[tuple[Path, int]] = []
    for subdir in sorted(root.iterdir()):
        if not subdir.is_dir():
            continue
        if subdir.name.startswith(".") or subdir.name in SKIP_DIRS:
            continue
        md_files = list(subdir.rglob("*.md"))
        count = len(md_files)
        if count < min_files:
            continue
        has_index = any((subdir / name).exists() for name in INDEX_NAMES)
        if not has_index:
            missing.append((subdir, count))
    return sorted(missing, key=lambda x: -x[1])


def _file_summary_line(path: Path, root: Path) -> str:
    rel = path.relative_to(root)
    return f"- [{path.stem}]({rel})"


def generate_index(directory: Path, dry_run: bool = False) -> bool:
    """Auto-generate a stub INDEX.md for a directory."""
    # Direct .md files (non-recursive) — used for the Contents section.
    md_files = [f for f in sorted(directory.glob("*.md")) if f.name not in INDEX_NAMES]
    # Subdirectories with .md content: compute count once to avoid duplicate rglob traversals.
    subdirs: list[tuple[Path, int]] = []
    for d in sorted(directory.iterdir()):
        if d.is_dir() and not d.name.startswith("."):
            subcount = sum(1 for _ in d.rglob("*.md"))
            if subcount > 0:
                subdirs.append((d, subcount))
    # Nothing to index at all — skip generation.
    if not md_files and not subdirs:
        return False

    rel_to_docs = directory.relative_to(DOCS_ROOT)
    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    title = directory.name.replace("-", " ").replace("_", " ").title()

    lines = [
        f"# {title}",
        "",
        f"> **Auto-generated index** — {now} | Edit this file to add descriptions.",
        f"> Directory: `docs/{rel_to_docs}/`",
        "",
    ]

    if md_files:
        lines += ["## Contents", ""]
        for f in md_files:
            rel = f.relative_to(directory)
            lines.append(f"- [{f.stem}]({rel})")

    # Add subdirectory links; only insert a leading blank line when a previous
    # section was emitted to avoid two consecutive blank lines in subdir-only indexes.
    if subdirs:
        if lines and lines[-1] != "":
            lines.append("")
        lines += ["## Subdirectories", ""]
        for d, subcount in subdirs:
            noun = "file" if subcount == 1 else "files"
            lines.append(f"- **[{d.name}/]({d.name}/)** — {subcount} {noun}")

    lines += [
        "",
        "---",
        "",
        "*Auto-generated by `scripts/ci/check_docs_index.py --generate`.*",
        "*Update this file with descriptions and cross-references.*",
    ]

    content = "\n".join(lines) + "\n"
    index_path = directory / "INDEX.md"

    if dry_run:
        print(f"  [dry-run] Would create: {index_path.relative_to(REPO_ROOT)} ({len(content)} chars)")
        return True

    index_path.write_text(content, encoding="utf-8")
    print(f"  ✅ Created: {index_path.relative_to(REPO_ROOT)}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Enforce INDEX.md presence in every docs/ subdirectory."
    )
    parser.add_argument(
        "--root",
        default=str(DOCS_ROOT),
        help=f"Root directory to check (default: {DOCS_ROOT})",
    )
    parser.add_argument(
        "--min-files",
        type=int,
        default=1,
        metavar="N",
        help="Only check dirs with at least N .md files (default: 1)",
    )
    parser.add_argument(
        "--generate",
        action="store_true",
        help="Auto-generate stub INDEX.md files for directories missing one",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without making changes (use with --generate)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 if any directories are missing INDEX.md",
    )
    args = parser.parse_args(argv)

    root = Path(args.root)
    if not root.exists():
        print(f"❌ Root directory does not exist: {root}", file=sys.stderr)
        return 1

    missing = find_dirs_without_index(root, min_files=args.min_files)

    if not missing:
        total = sum(1 for d in root.iterdir() if d.is_dir() and not d.name.startswith("."))
        print(f"✅ All {total} docs/ subdirectories have an INDEX.md")
        return 0

    print(f"{'[dry-run] ' if args.dry_run else ''}📋 {len(missing)} docs/ subdirectory/ies missing INDEX.md:\n")
    print(f"  {'Files':>6}  Directory")
    print(f"  {'------':>6}  ---------")
    for path, count in missing:
        rel = path.relative_to(REPO_ROOT)
        print(f"  {count:>6}  {rel}/")

    if args.generate:
        print(f"\n{'[dry-run] ' if args.dry_run else ''}Generating stub INDEX.md files...\n")
        generated = 0
        for path, _ in missing:
            if generate_index(path, dry_run=args.dry_run):
                generated += 1
        verb = "Would generate" if args.dry_run else "Generated"
        print(f"\n{verb} {generated} INDEX.md stub(s).")
        if not args.dry_run:
            print("Edit each INDEX.md to add meaningful descriptions and cross-references.")
        return 0

    print(
        f"\nRun with --generate to create stub INDEX.md files for all {len(missing)} directories."
    )
    print("Run with --generate --dry-run to preview changes first.")

    return 1 if args.strict else 0


if __name__ == "__main__":
    sys.exit(main())
