#!/usr/bin/env python3
"""
Phase 8.1: Generate Comprehensive Health Dashboard

Generates a real-time health dashboard from collected metrics.
Saves output to .codex/PHASE_8_1_HEALTH_DASHBOARD_LIVE.md
"""

import json
import sys
from datetime import datetime

def main():
    try:
        # Load enhanced metrics
        with open('.codex/metrics/enhanced_metrics.json') as f:
            metrics = json.load(f)

        # Create comprehensive dashboard update
        dashboard_content = f"""# Phase 8.1: Deployment Health Dashboard

**Last Updated**: {datetime.utcnow().isoformat()}Z
**Update Frequency**: Every 1 hour (automated)
**Status**: 🟢 OPERATIONAL
**Authority**: @mbaetiong (D-tier autonomous)

## �� Health Score: {metrics['aggregated'].get('health_score', 0)}/100

### Real-Time Metrics (28 Signals)

**Workflow Metrics**:
- Failure Rate: {metrics['aggregated'].get('total_failure_rate_percent', 0)}%
- Success Rate: {metrics['aggregated'].get('total_success_rate_percent', 0)}%
- Avg Duration: {metrics['aggregated'].get('avg_duration_seconds', 0)}s
- 24h Throughput: {metrics['aggregated'].get('total_throughput_24h', 0)} runs

**Infrastructure Health**:
- CPU Utilization: {metrics['signals']['infrastructure_metrics'].get('cpu_utilization_percent', 0)}%
- Memory Utilization: {metrics['signals']['infrastructure_metrics'].get('memory_utilization_percent', 0)}%
- Disk Utilization: {metrics['signals']['infrastructure_metrics'].get('disk_utilization_percent', 0)}%
- API Rate Limit: {metrics['signals']['infrastructure_metrics'].get('api_rate_limit_usage_percent', 0)}%

**Error Tracking**:
"""
        for error_type, count in metrics['signals']['error_metrics'].items():
            dashboard_content += f"- {error_type.replace('_', ' ').title()}: {count}\n"

        dashboard_content += f"""
**SLA Compliance**:
- Availability: {metrics['signals']['sla_metrics'].get('availability_percent', 0)}%
- MTTI: {metrics['signals']['sla_metrics'].get('mtti_minutes', 0)}min
- MTTR: {metrics['signals']['sla_metrics'].get('mttr_minutes', 0)}min
- P0 Incidents: {metrics['signals']['sla_metrics'].get('p0_incident_count_month', 0)}
- P1 Incidents: {metrics['signals']['sla_metrics'].get('p1_incident_count_month', 0)}

**Cache Effectiveness**:
- Build Cache Hit: {metrics['signals']['cache_metrics'].get('build_cache_hit_rate_percent', 0)}%
- Dependency Cache Hit: {metrics['signals']['cache_metrics'].get('dependency_cache_hit_rate_percent', 0)}%
- Artifact Cache Hit: {metrics['signals']['cache_metrics'].get('artifact_cache_hit_rate_percent', 0)}%

**Alert Status**: {metrics['aggregated'].get('overall_alert_status', 'unknown').upper()}

---

**Dashboard auto-generated by Phase 8.1 Enhanced Health Monitor**
Next update: {(datetime.utcnow().timestamp() + 3600):.0f} (UTC timestamp)
"""

        # Save dashboard
        with open('.codex/PHASE_8_1_HEALTH_DASHBOARD_LIVE.md', 'w') as f:
            f.write(dashboard_content)

        print("✓ Comprehensive dashboard generated")
        return 0

    except FileNotFoundError as e:
        print(f"✗ Error: {e}")
        return 1
    except json.JSONDecodeError as e:
        print(f"✗ JSON Error: {e}")
        return 1
    except Exception as e:
        print(f"✗ Unexpected error: {e}")
        return 1

if __name__ == '__main__':
    sys.exit(main())
