#!/usr/bin/env python3
"""Push Conflict Resolver for Copilot Cloud Agent sessions.

Handles the scenario reported in PR #4389 runs 3486 and 3489:

    "Changes were pushed to Copilot's branch while it was working,
     and Copilot was unable to merge its changes with the contents
     of the remote branch."

Root cause: Automated CI commits (``chore(d00): update session context
digest``, ``chore(auth): write provenance session token``,
``chore(manifest): auto-refresh CODEX_MANIFEST.json``) are pushed by
``github-actions[bot]`` to the agent's branch **while** the Copilot
Cloud Agent is composing its commit.  The agent's subsequent push is
rejected because the branch has diverged.

Strategy
--------
1. ``git fetch origin`` — refresh remote refs.
2. Detect how many commits behind ``HEAD`` is relative to the remote branch.
3. ``git pull --rebase --autostash`` — attempt clean rebase.
4. If conflicts arise, resolve auto-resolvable files:
   - ``CODEX_MANIFEST.json`` → take ``--theirs`` (auto-generated; main/remote is always authoritative)
   - ``.codex/agent_context.json`` → take ``--theirs``
   - ``.secrets.baseline`` → take ``--ours`` (per P-045 policy)
5. If unresolvable conflicts remain, abort rebase and report them.
6. Output a structured JSON result for CI / script consumption.

Usage
-----
    # Dry-run (show what would happen, no changes)
    python3 scripts/ci/push_conflict_resolver.py --dry-run

    # Apply (default)
    python3 scripts/ci/push_conflict_resolver.py

    # Specify branch explicitly
    python3 scripts/ci/push_conflict_resolver.py --branch copilot/add-full-path-to-init-tracing-docs
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

# ── Policy: which side to take for known auto-generated conflict files ─────────

# These files are always auto-generated by bots; the remote (theirs) version
# is the most recent and should be preferred.
_PREFER_THEIRS: frozenset[str] = frozenset({
    "CODEX_MANIFEST.json",
    ".codex/agent_context.json",
    ".codex/session_context_latest.md",
})

# These files should always keep the branch (ours) version per documented policy.
_PREFER_OURS: frozenset[str] = frozenset({
    ".secrets.baseline",  # P-045: always take ours
})


# ── Subprocess helpers ─────────────────────────────────────────────────────────

def _run(
    cmd: list[str],
    check: bool = True,
    capture: bool = True,
    env: dict | None = None,
) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        check=check,
        capture_output=capture,
        text=True,
        env=env,
    )


def _is_rebasing() -> bool:
    return (
        Path(".git/rebase-merge").exists()
        or Path(".git/rebase-apply").exists()
    )


def _conflicted_files() -> list[str]:
    result = _run(["git", "diff", "--name-only", "--diff-filter=U"], check=False)
    return [f.strip() for f in result.stdout.splitlines() if f.strip()]


def _current_branch() -> str:
    return _run(["git", "rev-parse", "--abbrev-ref", "HEAD"]).stdout.strip()


# ── Conflict resolution ─────────────────────────────────────────────────────────

def _resolve_known_conflicts(
    conflicts: list[str],
    dry_run: bool = False,
) -> tuple[list[str], list[str]]:
    """
    For each conflict, apply the appropriate resolution policy.

    Returns
    -------
    resolved : list[str]
        Paths that were auto-resolved (with the side taken noted).
    unresolved : list[str]
        Paths that require manual intervention.
    """
    resolved: list[str] = []
    unresolved: list[str] = []

    for f in conflicts:
        fname = Path(f).name
        if fname in _PREFER_THEIRS or f in _PREFER_THEIRS:
            if not dry_run:
                _run(["git", "checkout", "--theirs", f], check=False)
                _run(["git", "add", f], check=False)
            resolved.append(f"THEIRS:{f}")
        elif fname in _PREFER_OURS or f in _PREFER_OURS:
            if not dry_run:
                _run(["git", "checkout", "--ours", f], check=False)
                _run(["git", "add", f], check=False)
            resolved.append(f"OURS:{f}")
        else:
            unresolved.append(f)

    return resolved, unresolved


# ── Main logic ──────────────────────────────────────────────────────────────────

def resolve(branch: str = "", remote: str = "origin", dry_run: bool = False) -> dict:
    """
    Detect and resolve push conflicts.  Returns a result dict.

    The dict always contains:
      success : bool
      action  : str   — one of: no-op | rebase-clean | rebase-with-conflict-resolution
                                  | rebase-aborted | dry-run | fetch-failed
      resolved_files   : list[str]
      unresolved_files : list[str]
      commits_behind   : int
      error            : str | None
    """
    result: dict = {
        "success": False,
        "action": "none",
        "resolved_files": [],
        "unresolved_files": [],
        "commits_behind": 0,
        "error": None,
    }

    # 1. Fetch remote state
    print("📡 Fetching remote branch state…", file=sys.stderr)
    fetch = _run(["git", "fetch", remote], check=False)
    if fetch.returncode != 0:
        result["action"] = "fetch-failed"
        result["error"] = f"git fetch failed: {fetch.stderr.strip()}"
        return result

    # 2. Determine current branch if not supplied
    if not branch:
        branch = _current_branch()
    remote_ref = f"{remote}/{branch}"

    # 3. Check how far behind HEAD is
    behind_result = _run(
        ["git", "rev-list", "--count", f"HEAD..{remote_ref}"],
        check=False,
    )
    if behind_result.returncode != 0:
        # Remote ref doesn't exist — branch may be new; nothing to do
        result["success"] = True
        result["action"] = "no-op"
        return result

    commits_behind = int(behind_result.stdout.strip() or "0")
    result["commits_behind"] = commits_behind

    if commits_behind == 0:
        print("✅ Branch is up-to-date — no conflict resolution needed.", file=sys.stderr)
        result["success"] = True
        result["action"] = "no-op"
        return result

    print(
        f"⚠️  Branch is {commits_behind} commit(s) behind {remote_ref}",
        file=sys.stderr,
    )

    if dry_run:
        result["action"] = "dry-run"
        result["error"] = (
            f"{commits_behind} commits behind {remote_ref} (dry-run — no changes made). "
            "Run without --dry-run to apply."
        )
        return result

    # 4. Attempt clean rebase with autostash
    print("🔄 Attempting git pull --rebase --autostash…", file=sys.stderr)
    rebase = _run(
        ["git", "pull", "--rebase", "--autostash", remote, branch],
        check=False,
        capture=False,
    )

    if rebase.returncode == 0:
        result["success"] = True
        result["action"] = "rebase-clean"
        print("✅ Clean rebase succeeded.", file=sys.stderr)
        return result

    # 5. Rebase has conflicts — resolve known ones
    if not _is_rebasing():
        result["action"] = "rebase-failed-no-state"
        result["error"] = "git pull --rebase failed and no rebase state was created."
        return result

    conflicts = _conflicted_files()
    print(f"⚠️  Rebase conflicts in: {conflicts}", file=sys.stderr)

    resolved, unresolved = _resolve_known_conflicts(conflicts, dry_run=False)
    result["resolved_files"] = resolved

    if unresolved:
        # Cannot fully auto-resolve — abort to leave repo in clean state
        _run(["git", "rebase", "--abort"], check=False)
        result["action"] = "rebase-aborted"
        result["unresolved_files"] = unresolved
        result["error"] = (
            f"Could not auto-resolve conflicts in: {unresolved}. "
            "Rebase aborted. Manual intervention required before agent session."
        )
        return result

    # 6. All conflicts resolved — continue the rebase
    env_no_editor = {**__import__("os").environ, "GIT_EDITOR": "true"}
    cont = _run(
        ["git", "rebase", "--continue"],
        check=False,
        capture=False,
        env=env_no_editor,
    )
    if cont.returncode == 0:
        result["success"] = True
        result["action"] = "rebase-with-conflict-resolution"
        print("✅ Rebase completed after resolving known conflicts.", file=sys.stderr)
    else:
        _run(["git", "rebase", "--abort"], check=False)
        result["action"] = "rebase-aborted"
        result["error"] = (
            "git rebase --continue failed after resolving known conflicts. "
            "Rebase aborted."
        )

    return result


# ── Entry point ────────────────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--branch",
        default="",
        help="Branch name (default: auto-detected from current HEAD)",
    )
    p.add_argument(
        "--remote",
        default="origin",
        help="Remote name (default: origin)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would happen without making any changes",
    )
    p.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Output result as JSON (default: human-readable + JSON)",
    )
    return p.parse_args()


def main() -> int:
    args = _parse_args()
    result = resolve(branch=args.branch, remote=args.remote, dry_run=args.dry_run)
    print(json.dumps(result, indent=2))
    return 0 if result["success"] else 1


if __name__ == "__main__":
    sys.exit(main())
