
[project]
name = "codex-client"
version = "0.1.0"
description = "Codex tool-calling client for ITA"
requires-python = ">=3.10"
dependencies = [
  "openai>=1.51.0",
  "httpx==0.27.2",
  "pydantic==2.9.2",
  "anyio>=4.0.0",
]
