apiVersion: helm.sh/v1
kind: HelmValues
spec:
  replicaCount: 3

  image:
    repository: codex-ml
    pullPolicy: IfNotPresent
    tag: "1.0.0"

  service:
    type: ClusterIP
    port: 8000

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  ingress:
    enabled: false
    className: null
    annotations: {}
    hosts:
      - host: codex.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  env:
    - name: LOG_LEVEL
      value: INFO

  nodeSelector: {}
  tolerations: []
  affinity: {}
