# Default model configuration for lightweight training loops.
name: MiniLM
model_name: sshleifer/tiny-gpt2
model_name_or_path: ${.model_name}
pretrained_model_name_or_path: ${.model_name}
tokenizer_name: ${.model_name}
tokenizer_name_or_path: ${.model_name}
dtype: float32
precision: ${.dtype}
device: auto
lora:
  enabled: false
  enable: ${.enabled}
  r: 8
  lora_r: ${.r}
  lora_alpha: 16
  alpha: ${.lora_alpha}
  lora_dropout: 0.1
  dropout: ${.lora_dropout}
  bias: none
  target_modules:
    - q_proj
    - v_proj
  task_type: CAUSAL_LM
