# Default model configuration
name: MiniLM
pretrained_model_name_or_path: sshleifer/tiny-gpt2
tokenizer_name: ${pretrained_model_name_or_path}
model_name: ${pretrained_model_name_or_path}
dtype: float32
device: cpu
use_lora: ${lora.enabled}
lora_rank: ${lora.r}
lora_alpha: ${lora.lora_alpha}
lora:
  enabled: false
  r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  task_type: CAUSAL_LM
