"""SRE Monitoring Module — Real-time SLO tracking, anomaly detection, alert routing.

This module implements:
- Real-time SLO tracking: p50, p95, p99 latency percentiles
- Anomaly detection: deviation from baseline (>2 sigma)
- Alert routing: critical alerts to owner, normal to team
- Monitoring dashboard metrics
"""

import logging
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    """Alert severity levels."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class LatencyMetrics:
    """Latency percentiles and statistics."""

    p50_ms: float  # Median
    p95_ms: float
    p99_ms: float
    p999_ms: float
    min_ms: float
    max_ms: float
    mean_ms: float
    sample_count: int


@dataclass
class SLOTarget:
    """SLO target definition."""

    name: str
    target_pct: float  # e.g., 99.9
    window_minutes: int  # Measurement window
    threshold_ms: Optional[float] = None  # For latency-based SLOs


@dataclass
class MonitoringAlert:
    """Alert generated by monitoring."""

    alert_id: str
    timestamp: datetime
    severity: AlertSeverity
    metric_name: str
    metric_value: float
    threshold: float
    deviation_sigma: float  # Standard deviations from mean
    message: str
    routed_to: str  # "owner", "team", "escalation"


@dataclass
class MonitoringReport:
    """Comprehensive monitoring report."""

    timestamp: datetime
    window_start: datetime
    window_end: datetime
    slo_compliance_pct: float
    latency_metrics: Dict[str, LatencyMetrics]
    alerts: List[MonitoringAlert]
    anomalies_detected: List[str]
    error_rate_pct: float
    throughput_rps: float
    critical_alerts_count: int
    recommended_actions: List[str]


class SREMonitor:
    """Real-time SRE monitoring for production system."""

    def __init__(self):
        """Initialize SRE monitor with default SLO targets."""
        self.slo_targets = {
            "availability": SLOTarget(name="Availability", target_pct=99.9, window_minutes=30),
            "latency_p99": SLOTarget(
                name="Latency P99", target_pct=99.0, window_minutes=30, threshold_ms=200.0
            ),
            "error_rate": SLOTarget(name="Error Rate", target_pct=99.95, window_minutes=5),
        }
        self.alerts: List[MonitoringAlert] = []
        self.baseline_latency: Dict[str, LatencyMetrics] = {}
        self.created_at = datetime.now(timezone.utc)
        self._initialize_baseline()

    def _initialize_baseline(self) -> None:
        """Initialize baseline latency metrics."""
        # Normal baseline for healthy system
        self.baseline_latency["p99"] = LatencyMetrics(
            p50_ms=10.0,
            p95_ms=50.0,
            p99_ms=150.0,
            p999_ms=500.0,
            min_ms=1.0,
            max_ms=600.0,
            mean_ms=25.0,
            sample_count=10000,
        )
        logger.info("SRE Monitor baseline initialized")

    def record_latencies(self, latencies_ms: List[float], lane_id: str = "default") -> None:
        """Record latency samples."""
        if not latencies_ms:
            return

        sorted_latencies = sorted(latencies_ms)
        n = len(sorted_latencies)

        metrics = LatencyMetrics(
            p50_ms=sorted_latencies[int(n * 0.50)],
            p95_ms=sorted_latencies[int(n * 0.95)],
            p99_ms=sorted_latencies[int(n * 0.99)],
            p999_ms=sorted_latencies[int(n * 0.999)] if n > 1000 else sorted_latencies[-1],
            min_ms=min(latencies_ms),
            max_ms=max(latencies_ms),
            mean_ms=sum(latencies_ms) / n,
            sample_count=n,
        )

        # Check for anomalies
        self._check_latency_anomaly(metrics, lane_id)

        logger.info(
            f"Lane {lane_id}: p50={metrics.p50_ms:.1f}ms, "
            f"p99={metrics.p99_ms:.1f}ms, p999={metrics.p999_ms:.1f}ms"
        )

    def _check_latency_anomaly(self, current: LatencyMetrics, lane_id: str) -> None:
        """Check if current latencies deviate from baseline (anomaly detection)."""
        baseline = self.baseline_latency.get("p99")
        if not baseline:
            return

        # Calculate standard deviation
        current_p99_deviation = (current.p99_ms - baseline.p99_ms) / baseline.p99_ms
        sigma_deviation = current_p99_deviation / 0.1  # Assume 10% normal variation = 1 sigma

        if abs(sigma_deviation) > 2.0:
            severity = AlertSeverity.CRITICAL if sigma_deviation > 3.0 else AlertSeverity.HIGH

            alert = MonitoringAlert(
                alert_id=f"latency-{datetime.now(timezone.utc).timestamp()}",
                timestamp=datetime.now(timezone.utc),
                severity=severity,
                metric_name=f"latency_p99_{lane_id}",
                metric_value=current.p99_ms,
                threshold=baseline.p99_ms * 1.2,
                deviation_sigma=sigma_deviation,
                message=f"P99 latency anomaly: {current.p99_ms:.1f}ms "
                f"(baseline: {baseline.p99_ms:.1f}ms, deviation: {sigma_deviation:.1f}σ)",
                routed_to="owner" if severity == AlertSeverity.CRITICAL else "team",
            )

            self.alerts.append(alert)
            logger.warning(f"Latency anomaly detected: {alert.message}")

    def get_slo_compliance(self, target_name: str, compliance_rate: float) -> MonitoringAlert:
        """Generate alert for SLO non-compliance."""
        target = self.slo_targets.get(target_name)
        if not target:
            return None

        if compliance_rate < target.target_pct:
            deviation = (target.target_pct - compliance_rate) / target.target_pct
            severity = AlertSeverity.CRITICAL if deviation > 0.05 else AlertSeverity.HIGH

            alert = MonitoringAlert(
                alert_id=f"slo-{datetime.now(timezone.utc).timestamp()}",
                timestamp=datetime.now(timezone.utc),
                severity=severity,
                metric_name=f"slo_{target_name}",
                metric_value=compliance_rate,
                threshold=target.target_pct,
                deviation_sigma=deviation,
                message=f"SLO breach: {target_name} at {compliance_rate:.2f}% "
                f"(target: {target.target_pct:.2f}%)",
                routed_to="owner" if severity == AlertSeverity.CRITICAL else "team",
            )

            self.alerts.append(alert)
            logger.error(f"SLO non-compliance: {alert.message}")
            return alert

        return None

    def generate_monitoring_report(
        self,
        slo_compliance_pct: float = 99.5,
        error_rate_pct: float = 0.3,
        throughput_rps: float = 5000.0,
    ) -> MonitoringReport:
        """Generate comprehensive monitoring report."""
        critical_alerts = [a for a in self.alerts if a.severity == AlertSeverity.CRITICAL]
        anomalies = [a.message for a in self.alerts if a.severity in (AlertSeverity.HIGH, AlertSeverity.CRITICAL)]

        recommendations = []
        if slo_compliance_pct < 99.9:
            recommendations.append("Investigate SLO non-compliance; check error rates and latencies")
        if error_rate_pct > 1.0:
            recommendations.append("Error rate elevated; review recent deployments and logs")
        if len(critical_alerts) > 0:
            recommendations.append("Critical alerts present; escalate to on-call SRE immediately")

        window_start = datetime.now(timezone.utc) - timedelta(minutes=30)
        window_end = datetime.now(timezone.utc)

        report = MonitoringReport(
            timestamp=datetime.now(timezone.utc),
            window_start=window_start,
            window_end=window_end,
            slo_compliance_pct=slo_compliance_pct,
            latency_metrics={
                "p99": self.baseline_latency.get("p99", LatencyMetrics(0, 0, 0, 0, 0, 0, 0, 0)),
            },
            alerts=self.alerts[-20:] if len(self.alerts) > 20 else self.alerts,
            anomalies_detected=anomalies,
            error_rate_pct=error_rate_pct,
            throughput_rps=throughput_rps,
            critical_alerts_count=len(critical_alerts),
            recommended_actions=recommendations,
        )

        return report

    def get_all_alerts(self) -> List[MonitoringAlert]:
        """Get all alerts."""
        return self.alerts

    def clear_old_alerts(self, minutes_to_keep: int = 1440) -> int:
        """Clear alerts older than specified minutes. Returns count of cleared alerts."""
        cutoff_time = datetime.now(timezone.utc) - timedelta(minutes=minutes_to_keep)
        before_count = len(self.alerts)
        self.alerts = [a for a in self.alerts if a.timestamp > cutoff_time]
        cleared = before_count - len(self.alerts)
        logger.info(f"Cleared {cleared} old alerts")
        return cleared
