version: 1
bypass: false
log_path: .codex/safety/events.ndjson
description: Default policy for prompt/output safeguards in offline demos.
allow:
  literals:
    - "rm -rf build"
    - "drop database schema_example"
  patterns:
    - pattern: "(?i)test(_|-)?password"
rules:
  - id: destructive-shell
    description: Block destructive shell commands and self-harm instructions.
    reason: destructive_command
    severity: high
    action: block
    applies_to: [prompt, output]
    match:
      literals:
        - "rm -rf /"
        - "format c:"
        - "mkfs"
        - "shutdown -h now"
        - "kill yourself"
        - "weapon schematic"
        - "drop database"
  - id: secrets-redact
    description: Redact obvious secrets and access tokens.
    reason: credential_leak
    severity: high
    action: redact
    replacement: "{REDACTED:SECRET}"
    applies_to: [prompt, output]
    match:
      patterns:
        - "(?i)password\\s*[:=]\\s*\\S+"
        - "(?i)api[_-]?key\\s*[:=]\\s*\\S+"
        - "AKIA[0-9A-Z]{16}"
  - id: pii-redact
    description: Redact US-style SSNs.
    reason: pii_redaction
    severity: medium
    action: redact
    replacement: "{REDACTED:PII}"
    applies_to: [prompt, output]
    match:
      patterns:
        - "\\b\\d{3}-\\d{2}-\\d{4}\\b"
  - id: jailbreak-block
    description: Block jailbreak-style prompt injection attempts.
    reason: jailbreak
    severity: medium
    action: block
    applies_to: [prompt]
    match:
      patterns:
        - "(?i)ignore all (previous|prior) instructions"
        - "(?i)do anything now"
