training:
  seed: 42
  learning_rate: 0.0003
  batch_size: 32
  max_epochs: 5
  scheduler: linear
  warmup_steps: 0
  gradient_accumulation: 1
  tensorboard: true
  mlflow_enable: false
  model: minilm
  output_dir: runs/default
  checkpoint_dir: runs/default/checkpoints
  checkpoint_every_n_steps: 50
  dataset:
    train_path: data/train_samples.jsonl
    eval_path: null
    format: jsonl
    train_texts: []
    eval_texts: []
  logging:
    enable_tensorboard: true
    mlflow_enable: false
