"""Default training configuration for HuggingFace Trainer.

This file provides a minimal set of sensible defaults for the training
engine tests. Values can be overridden at runtime via CLI flags or Hydra
configuration. Only keys understood by ``transformers.TrainingArguments``
or consumed by helper utilities should be declared here.
"""

# Number of training epochs
num_train_epochs: 1

# Optimizer hyperparameters
learning_rate: 0.001

# Effective batch size will be
# ``per_device_train_batch_size * gradient_accumulation_steps``
per_device_train_batch_size: 2
gradient_accumulation_steps: 1

# Optional precision / LoRA fields parsed separately
precision: fp32
lora_r: null
lora_alpha: 16
