rules:
  - id: py-requests-verify-disabled
    message: "requests called with verify=False disables TLS verification"
    languages: [python]
    severity: WARNING
    patterns:
      - pattern-either:
          - pattern: requests.get(..., verify=False, ...)
          - pattern: requests.post(..., verify=False, ...)
          - pattern: requests.put(..., verify=False, ...)
          - pattern: requests.patch(..., verify=False, ...)
          - pattern: requests.delete(..., verify=False, ...)
          - pattern: requests.head(..., verify=False, ...)
          - pattern: requests.options(..., verify=False, ...)

  - id: py-subprocess-shell-true
    message: "subprocess with shell=True can lead to command injection"
    languages: [python]
    severity: ERROR
    patterns:
      - pattern-either:
          - pattern: subprocess.run(..., shell=True, ...)
          - pattern: subprocess.Popen(..., shell=True, ...)
          - pattern: subprocess.call(..., shell=True, ...)
          - pattern: subprocess.check_call(..., shell=True, ...)
          - pattern: subprocess.check_output(..., shell=True, ...)

  - id: py-yaml-unsafe-load
    message: "Use yaml.safe_load()/SafeLoader (avoid unsafe loaders)"
    languages: [python]
    severity: ERROR
    patterns:
      - pattern: yaml.load(...)
      - pattern-not: yaml.load(..., Loader=yaml.SafeLoader, ...)
      - pattern-not: yaml.load(..., Loader=yaml.CSafeLoader, ...)
      - pattern-not: yaml.load_all(..., Loader=yaml.SafeLoader, ...)
      - pattern-not: yaml.full_load(...)
      - pattern-not: yaml.safe_load(...)

  - id: py-pickle-load
    message: "Avoid loading pickles from untrusted sources"
    languages: [python]
    severity: WARNING
    pattern-either:
      - pattern: pickle.load(...)
      - pattern: pickle.loads(...)
