# Offline GPT-2 tokenizer configuration.
# Points the tokenizer registry at locally cached vocabularies.
defaults:
  - override /tokenizer: base

tokenizer:
  name: gpt2-offline
  name_or_path: ${oc.env:CODEX_ML_GPT2_TOKENIZER_PATH,${oc.env:CODEX_ML_OFFLINE_MODELS_DIR,${hydra:runtime.cwd}/artifacts/models/gpt2}}
  use_fast: true
