# Safe baseline defaults for Codex ML Hydra runs (offline-friendly)
# Apply with: python -m codex_ml.cli.hydra_main --config-path configs --config-name default
defaults:
  - model: base
  - training: base
  - data: tiny
  - _self_

model_name: ${model.model_name_or_path}
dataset_path: ${data.dataset_path}
epochs: ${training.epochs}
batch_size: ${training.batch_size}
learning_rate: ${training.learning_rate}
seed: ${training.seed}
deterministic: ${training.deterministic}
use_lora: ${model.lora.enabled}
lora_rank: ${model.lora.r}
lora_alpha: ${model.lora.lora_alpha}
device: ${model.device}
dtype: ${model.dtype}
logging:
  enable_tensorboard: ${training.logging.enable_tensorboard}
  enable_mlflow: ${training.logging.enable_mlflow}
  enable_wandb: false
