# Canonical defaults list for Codex training runs.
# See hydra 'Defaults List' docs.
defaults:
  - data: tiny
  - model: toy
  - train: small
  - tracking: offline
  - _self_

# Top-level composite (merged from groups)
run:
  seed: 42
  output_dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

training:
  epochs: 1
  batch_size: 8
  grad_clip_norm: null
  seed: 42

logging:
  ndjson_log_path: "artifacts/train.ndjson"

tracking:
  mlflow:
    enable: false
    tracking_uri: "file://./mlruns"
  wandb:
    enable: false
    mode: "offline"
