# Safe baseline defaults for Codex ML Hydra runs (offline-friendly)
# Apply with: python -m codex_ml.cli.hydra_main --config-path configs --config-name default
model_name: "sshleifer/tiny-gpt2"
dataset_path: "data/tiny_corpus.txt"
epochs: 1
batch_size: 2
learning_rate: 5e-5
seed: 42
deterministic: true
use_lora: false
lora_rank: 8
lora_alpha: 16
device: "cpu"
dtype: "float32"
logging:
  enable_tensorboard: false
  enable_mlflow: false
  enable_wandb: false
