# Map interface names to implementation paths and optional kwargs.
# tokenizer:
#   path: yourpkg.tokenizers.hf:HFTokenizer
#   kwargs: {}
# reward_model:
#   path: yourpkg.rewards.simple:SimpleReward
#   kwargs: {}
# rl_agent:
#   path: yourpkg.rl.ppo:PPOAgent
#   kwargs: {}
