# BEGIN: CODEX_IFACE_CONFIG
# Example mapping of interface groups to concrete implementations
tokenizer:
  path: codex_ml.interfaces.tokenizer:WhitespaceTokenizer
  kwargs:
    lowercase: false
reward_model:
  path: codex_ml.interfaces.reward_model:HeuristicRewardModel
  kwargs: {}
rl_agent:
  path: codex_ml.interfaces.rl:BanditRLAgent
  kwargs: {}
# END: CODEX_IFACE_CONFIG
