#!/usr/bin/env python3
"""Generate __init__.py files for codex packages.

This script automatically generates __init__.py files with proper exports
for all codex packages to ensure consistency and prevent manual maintenance drift.
"""
from pathlib import Path
import logging
logger = logging.getLogger(__name__)
import ast
import sys
from typing import List

CODEX_PACKAGES = [
    "src/codex",
    "src/codex/logging",
    "src/codex/cli",
    "src/codex/analyze",
    "src/codex/analyze/static",
    "src/codex/analyze/runtime",
]


def extract_public_symbols(filepath: Path) -> List[str]:
    """Extract public classes, functions, and constants from a Python file."""
    try:
        tree = ast.parse(filepath.read_text(), filename=str(filepath))
    except (SyntaxError, UnicodeDecodeError):
        logger.debug("Exception caught, returning", exc_info=True)
        return []

    symbols = []
    for node in tree.body:
        # Classes and functions
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                symbols.append(node.name)
        # Explicit __all__ definition
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    # Parse the __all__ list if it exists
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant):
                                symbols.append(elt.value)
                            elif isinstance(elt, ast.Str):  # Python 3.7 compat
                                symbols.append(elt.s)
    return symbols


def generate_init_content(package_dir: Path) -> str:
    """Generate __init__.py content for a package directory."""
    package_dir = package_dir.resolve()
    modules = []
    subpackages = []

    # Scan directory
    for item in sorted(package_dir.iterdir()):
        if item.name == "__init__.py":
            continue

        if item.suffix == ".py" and not item.name.startswith("_"):
            module_name = item.stem
            modules.append(module_name)
        elif item.is_dir() and (item / "__init__.py").exists():
            subpackages.append(item.name)

    # Build content
    lines = [
        '"""Auto-generated package initialization for codex."""',
        "# AUTO-GENERATED by scripts/generate_codex_init.py - DO NOT EDIT",
        "# To regenerate: python scripts/generate_codex_init.py",
        "",
    ]

    # Import subpackages first
    for subpkg in subpackages:
        lines.append(f"from . import {subpkg}")

    if subpackages and modules:
        lines.append("")

    # Import modules
    for module in modules:
        lines.append(f"from . import {module}")

    if modules or subpackages:
        lines.append("")

    # Build __all__
    all_items = []
    all_items.extend(subpackages)
    all_items.extend(modules)

    if all_items:
        lines.append(f"__all__ = {sorted(all_items)!r}")

    return "\n".join(lines) + "\n"


def main():
    """Main entry point."""
    repo_root = Path(__file__).parent.parent
    
    if len(sys.argv) > 1:
        packages = [repo_root / arg for arg in sys.argv[1:]]
    else:
        packages = [repo_root / pkg for pkg in CODEX_PACKAGES]

    changed_count = 0
    unchanged_count = 0

    for package_path in packages:
        if not package_path.exists():
            print(f"⚠ Warning: {package_path} does not exist")
            continue

        init_file = package_path / "__init__.py"
        
        # Check if file has DO NOT EDIT marker - if not, skip to preserve manual edits
        if init_file.exists():
            content = init_file.read_text()
            if "DO NOT EDIT" not in content and "AUTO-GENERATED" not in content:
                print(f"ℹ {init_file}: Skipped (manual edits preserved)")
                continue
        
        new_content = generate_init_content(package_path)

        if init_file.exists():
            old_content = init_file.read_text()
            if old_content == new_content:
                print(f"✓ {init_file}: No changes needed")
                unchanged_count += 1
                continue

        init_file.write_text(new_content)
        print(f"✓ {init_file}: Updated")
        changed_count += 1

    print(f"\n{changed_count} file(s) updated, {unchanged_count} file(s) unchanged")
    return 0 if changed_count == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
