#!/usr/bin/env python3
"""
Merge multiple SARIF files into a single report.

Phase 18.2: CI/CD Pipeline Optimization
Created: 2026-01-18

This script merges multiple SARIF (Static Analysis Results Interchange Format)
files generated by CodeQL chunked analysis into a single consolidated report.

Usage:
    python merge_sarif.py --input-dir ./sarif-results --output merged.sarif
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def merge_sarif_files(input_dir: Path, output_file: Path) -> dict[str, Any]:
    """
    Merge all SARIF files in input_dir into a single report.
    
    Args:
        input_dir: Directory containing SARIF files to merge
        output_file: Path to write the merged SARIF file
        
    Returns:
        The merged SARIF data structure
    """
    merged: dict[str, Any] = {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": []
    }
    
    # Find all SARIF files
    sarif_files = list(input_dir.glob("*.sarif"))
    sarif_files.extend(input_dir.glob("**/*.sarif"))
    sarif_files = list(set(sarif_files))  # Remove duplicates
    
    if not sarif_files:
        logger.warning(f"No SARIF files found in {input_dir}")
        return merged
    
    logger.info(f"Found {len(sarif_files)} SARIF files to merge")
    
    total_results = 0
    for sarif_file in sorted(sarif_files):
        try:
            with open(sarif_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            
            if "runs" in data:
                for run in data["runs"]:
                    # Track results count
                    results = run.get("results", [])
                    total_results += len(results)
                    
                    # Add source file metadata
                    run["properties"] = run.get("properties", {})
                    run["properties"]["sourceFile"] = str(sarif_file.name)
                    run["properties"]["mergedAt"] = datetime.now(timezone.utc).isoformat()
                    
                    merged["runs"].append(run)
                
                logger.info(f"Merged {sarif_file.name}: {len(data.get('runs', []))} runs")
            else:
                logger.warning(f"No 'runs' found in {sarif_file}")
                
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON in {sarif_file}: {e}")
        except OSError as e:
            logger.error(f"Error reading {sarif_file}: {e}")
    
    # Add merge metadata
    merged["properties"] = {
        "mergedAt": datetime.now(timezone.utc).isoformat(),
        "sourceFiles": [str(f.name) for f in sarif_files],
        "totalRuns": len(merged["runs"]),
        "totalResults": total_results
    }
    
    # Write merged output
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(merged, f, indent=2)
    
    logger.info(f"Merged SARIF written to {output_file}")
    logger.info(f"Total: {len(merged['runs'])} runs, {total_results} results")
    
    return merged


def validate_sarif(sarif_data: dict[str, Any]) -> bool:
    """
    Validate that a SARIF data structure is well-formed.
    
    Args:
        sarif_data: The SARIF data to validate
        
    Returns:
        True if valid, False otherwise
    """
    required_fields = ["version", "runs"]
    
    for field in required_fields:
        if field not in sarif_data:
            logger.error(f"Missing required field: {field}")
            return False
    
    if sarif_data.get("version") != "2.1.0":
        logger.warning(f"Unexpected SARIF version: {sarif_data.get('version')}")
    
    if not isinstance(sarif_data.get("runs"), list):
        logger.error("'runs' must be a list")
        return False
    
    return True


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Merge multiple SARIF files into a single report",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --input-dir ./sarif-results --output merged.sarif
  %(prog)s -i . -o combined-results.sarif --validate
        """
    )
    parser.add_argument(
        "--input-dir", "-i",
        type=Path,
        required=True,
        help="Directory containing SARIF files to merge"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        required=True,
        help="Output file path for merged SARIF"
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate the merged SARIF output"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose output"
    )
    
    args = parser.parse_args()
    
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    # Validate input directory
    if not args.input_dir.exists():
        logger.error(f"Input directory does not exist: {args.input_dir}")
        return 1
    
    if not args.input_dir.is_dir():
        logger.error(f"Input path is not a directory: {args.input_dir}")
        return 1
    
    # Merge SARIF files
    try:
        merged = merge_sarif_files(args.input_dir, args.output)
    except Exception as e:
        logger.error(f"Error merging SARIF files: {e}")
        return 1
    
    # Optionally validate output
    if args.validate:
        if validate_sarif(merged):
            logger.info("Merged SARIF is valid")
        else:
            logger.error("Merged SARIF validation failed")
            return 1
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
