#!/usr/bin/env python3
"""
Phase 6: Philosophy Reading/Writing Automation — Philosophy Parser

Reads structured philosophy/reasoning documents from docs/ and memory/,
generates Markdown synthesis outputs, and schedules them between sessions.

Usage:
    python scripts/philosophy_parser.py parse  [--path PATH]
    python scripts/philosophy_parser.py write  [--topic TOPIC] [--template basic|structured]
    python scripts/philosophy_parser.py status
"""
from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).parent.parent
PHILOSOPHY_DIR = REPO_ROOT / "memory" / "philosophy"
DOCS_DIR = REPO_ROOT / "docs"

# ── Templates ──────────────────────────────────────────────────────────────────

TEMPLATES: dict[str, str] = {
    "basic": """\
# {topic}

**Generated:** {timestamp}

## Premise

{premise}

## Observations

{observations}

## Conclusion

{conclusion}
""",
    "structured": """\
# {topic}

**Generated:** {timestamp}
**Confidence:** {confidence}

## Axiomatic Foundation

{premise}

## Evidence Synthesis

{observations}

## Derived Conclusion

{conclusion}

## Open Questions

{questions}

---
*Auto-generated by philosophy_parser.py*
""",
}

# ── Default content constants ─────────────────────────────────────────────────

_DEFAULT_PREMISE = (
    "Autonomous agents operate more effectively when they maintain persistent "
    "memory, reason under uncertainty, and enforce finite resource budgets."
)
_DEFAULT_CONCLUSION = (
    "Continuous introspection and bounded computation enable sustainable "
    "autonomous operation with minimal human intervention."
)
_DEFAULT_QUESTIONS = (
    "- How should confidence decay over stale observations?\n"
    "- What is the optimal session cadence for this codebase?\n"
    "- How to balance exploration vs exploitation in action selection?"
)

# ── Parser ─────────────────────────────────────────────────────────────────────


def _extract_headings(text: str) -> list[dict[str, Any]]:
    """Extract headings and their immediate paragraph content."""
    headings = []
    current: Optional[dict] = None
    for line in text.splitlines():
        m = re.match(r'^(#{1,4})\s+(.*)', line)
        if m:
            if current:
                headings.append(current)
            current = {"level": len(m.group(1)), "title": m.group(2).strip(), "content": ""}
        elif current is not None:
            current["content"] += line + "\n"
    if current:
        headings.append(current)
    return headings


def _count_words(text: str) -> int:
    return len(re.findall(r'\w+', text))


def parse_document(path: Path) -> dict[str, Any]:
    """Parse a Markdown document and return structured analysis."""
    text = path.read_text(encoding="utf-8", errors="replace")
    headings = _extract_headings(text)
    word_count = _count_words(text)
    lines = text.splitlines()

    # Extract key concepts (capitalized multi-word phrases, simplified)
    concepts = list(dict.fromkeys(re.findall(r'\b[A-Z][A-Za-z]+(?: [A-Z][A-Za-z]+)+', text)))[:10]

    # Extract action items using a regex capture to reliably extract text after
    # the "- [ ]" / "- [x]" prefix, avoiding lstrip() mangling of content.
    # The trailing .strip() removes any surrounding whitespace from the capture.
    action_items = [
        m.group(1).strip()
        for line in lines
        if (m := re.match(r'^\s*-\s*\[[ x]\]\s*(.*)$', line))
    ]

    return {
        "path": str(path.relative_to(REPO_ROOT)),
        "word_count": word_count,
        "line_count": len(lines),
        "heading_count": len(headings),
        "headings": [{"level": h["level"], "title": h["title"]} for h in headings],
        "concepts": concepts,
        "action_items": action_items[:10],
    }


def cmd_parse(path_arg: Optional[str] = None) -> int:
    """Parse a document or scan docs/ for philosophy/reasoning docs."""
    if path_arg:
        target = Path(path_arg) if Path(path_arg).is_absolute() else REPO_ROOT / path_arg
        if not target.exists():
            print(f"ERROR: File not found: {target}", file=sys.stderr)
            return 1
        result = parse_document(target)
        print(json.dumps(result, indent=2, default=str))
        return 0

    # Scan docs/ for relevant documents
    patterns = ["**/ROADMAP*.md", "**/OPERATIONAL*.md", "**/AGENT*.md", "**/POLICY*.md"]
    found = []
    for pattern in patterns:
        found.extend(DOCS_DIR.glob(pattern))

    if not found:
        print("No philosophy/reasoning documents found in docs/")
        return 0

    results = []
    for doc in found[:20]:
        r = parse_document(doc)
        results.append(r)
        print(f"Parsed: {r['path']} ({r['word_count']} words, {r['heading_count']} headings)")

    # Save index
    PHILOSOPHY_DIR.mkdir(parents=True, exist_ok=True)
    index_path = PHILOSOPHY_DIR / "index.json"
    index_path.write_text(json.dumps(results, indent=2, default=str) + "\n", encoding="utf-8")
    print(f"\nIndex saved: {index_path}")
    return 0


def cmd_write(topic: str = "Agent Reasoning Synthesis", template: str = "basic") -> int:
    """Generate a philosophy document from a template."""
    PHILOSOPHY_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc)

    # Load observations from session tracker if available
    observations_lines = []
    session_dir = REPO_ROOT / "memory" / "sessions"
    for sf in sorted(session_dir.glob("session_*.json"), reverse=True)[:3]:
        try:
            sess = json.loads(sf.read_text(encoding="utf-8"))
            label = sess.get("label", sess.get("session_id", "?")[:12])
            outcome = sess.get("outcome", "unknown")
            observations_lines.append(f"- Session `{label}`: outcome={outcome}")
        except (json.JSONDecodeError, OSError, KeyError) as exc:
            log.debug("Skipping session file %s: %s", sf.name, exc)

    tmpl_text = TEMPLATES.get(template, TEMPLATES["basic"])
    content = tmpl_text.format(
        topic=topic,
        timestamp=ts.isoformat(),
        confidence="medium",
        premise=_DEFAULT_PREMISE,
        observations="\n".join(observations_lines) or "- No recent session data available",
        conclusion=_DEFAULT_CONCLUSION,
        questions=_DEFAULT_QUESTIONS,
    )

    slug = re.sub(r'\W+', '_', topic.lower())[:30]
    ts_str = ts.strftime("%Y%m%d_%H%M%S")
    out_path = PHILOSOPHY_DIR / f"{ts_str}_{slug}.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"Document written: {out_path}")
    return 0


def cmd_status() -> int:
    """Show philosophy memory status."""
    if not PHILOSOPHY_DIR.exists():
        print("Philosophy memory directory not yet created.")
        return 0
    docs = list(PHILOSOPHY_DIR.glob("*.md"))
    index = PHILOSOPHY_DIR / "index.json"
    print(f"Philosophy docs:  {len(docs)}")
    print(f"Index available:  {'yes' if index.exists() else 'no'}")
    for doc in sorted(docs, reverse=True)[:5]:
        print(f"  - {doc.name}")
    return 0


# ── CLI ────────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_parse = sub.add_parser("parse", help="Parse document(s)")
    p_parse.add_argument("--path", default=None)

    p_write = sub.add_parser("write", help="Generate a philosophy document")
    p_write.add_argument("--topic", default="Agent Reasoning Synthesis")
    p_write.add_argument("--template", choices=list(TEMPLATES.keys()), default="basic")

    sub.add_parser("status", help="Show philosophy memory status")

    args = parser.parse_args()

    if args.cmd == "parse":
        return cmd_parse(args.path)
    if args.cmd == "write":
        return cmd_write(topic=args.topic, template=args.template)
    if args.cmd == "status":
        return cmd_status()
    return 0


if __name__ == "__main__":
    sys.exit(main())
