#!/usr/bin/env python3
"""
Refresh Requirements Lock

Purpose:
    Command-line utility (see argument parser for details)

Usage:
    python scripts/refresh_requirements_lock.py [options]

    Examples:
    $ python scripts/refresh_requirements_lock.py --help

Arguments:
    [To be documented]

Environment Variables:
    [To be documented]

Dependencies:
    [To be documented]

Exit Codes:
    0: Success
    1: Error

Author: Codex Team
Last Updated: 2026-01-16
"""


from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


import argparse
import datetime as _dt
import os
import subprocess
import sys

try:  # Python 3.11+ stdlib
    import tomllib  # type: ignore[attr-defined]
except ModuleNotFoundError:  # Python 3.10 fallback
    import tomli as tomllib  # type: ignore[assignment]
from collections.abc import Callable, Iterable
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import InvalidVersion, Version

ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "requirements/lock.txt"
REQ_TXT = ROOT / "requirements/base.txt"
PYPROJECT = ROOT / "pyproject.toml"
ERROR_DIR = ROOT / ".codex" / "reports"

PYTHON_TARGET = "3.12"
COMPILE_COMMAND = [
    "uv",
    "pip",
    "compile",
    "pyproject.toml",
    "requirements/base.txt",
    "--extra",
    "dev",
    "--extra",
    "test",
    "--extra",
    "ml",
    "--extra",
    "logging",
    "--extra",
    "tracking",
    "--extra",
    "train",
    "--extra",
    "cli",
    "--extra",
    "monitoring",
    "--extra",
    "ops",
    "--extra",
    "perf",
    "--extra",
    "tokenizers",
    "--extra",
    "tokenizer",
    "--extra",
    "configs",
    "--extra",
    "dist",
    "--python-version",
    PYTHON_TARGET,
    "--output-file",
    "requirements/lock.txt",
]


def _today_slug() -> str:
    return _dt.datetime.now(tz=_dt.timezone.utc).strftime("%Y-%m-%d")


def _timestamp() -> str:
    from codex.utils.path_utils import windows_safe_timestamp
    return windows_safe_timestamp(fmt="iso")


def _error_file() -> Path:
    return ERROR_DIR / f"errors_{_today_slug()}.md"


def _ensure_error_dir() -> None:
    ERROR_DIR.mkdir(parents=True, exist_ok=True)


def log_error(step: str, message: str, context: str, question: str) -> None:
    """Append a structured error entry for the given step."""
    _ensure_error_dir()
    entry = "\n".join(
        [
            "---",
            f"### Error — {step}",
            f"- **Timestamp:** {_timestamp()}",
            f"- **Message:** {message}",
            "- **Context:**",
            "```text",
            context.strip() or "<none>",
            "```",
            f"- **Clarification:** {question}",
            "---",
            "",
        ]
    )
    with _error_file().open("a", encoding="utf-8") as handle:
        handle.write(entry)


StepFn = Callable[[], None]


def run_step(name: str, func: StepFn) -> bool:
    try:
        func()
        print(f"[OK ] {name}")
        return True
    except Exception as exc:  # noqa: BLE001 - explicit resilience per requirements
        log_error(
            name,
            message=str(exc),
            context=f"cwd={os.getcwd()}\npython={' '.join(sys.version.split())}",
            question=f"What adjustments are needed to complete step '{name}' successfully?",
        )
        print(f"[WARN] {name} failed: {exc}", file=sys.stderr)
        return False


def generate_lockfile() -> None:
    """Compile requirements/lock.txt using uv with all extras."""
    result = subprocess.run(COMPILE_COMMAND, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"uv pip compile failed\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    _inject_provenance_header(COMPILE_COMMAND)


def _inject_provenance_header(cmd: Iterable[str]) -> None:
    """Ensure the lockfile header documents the provenance command."""
    if not LOCK_PATH.exists():
        raise FileNotFoundError("requirements/lock.txt was not generated")
    text = LOCK_PATH.read_text(encoding="utf-8")
    lines = text.splitlines()
    provenance = "# Atomic Diff 5 provenance: docs/suggested_tasks/remediation_plan_status_update_2025-09-17.md (dependency locking guidance)"
    command_line = "#    " + " ".join(cmd)
    header_lines = [
        "# This file was autogenerated by uv via the following command:",
        command_line,
        provenance,
        f"# Python lock target: {PYTHON_TARGET}",
    ]

    # Remove any existing autogenerated header to avoid duplication.
    rest: list[str] = []
    skip_prefixes = {
        "# This file was autogenerated by uv via",
        "#    uv pip compile",
        "# Atomic Diff 5 provenance:",
        "# Python lock target:",
    }
    for line in lines:
        if any(line.startswith(prefix) for prefix in skip_prefixes):
            continue
        rest.append(line)

    new_text = "\n".join(header_lines + rest)
    LOCK_PATH.write_text(new_text + "\n", encoding="utf-8")


def _load_lock_versions() -> dict[str, tuple[Requirement, str | None]]:
    """Parse the lockfile and return requirement -> pinned version."""
    lock_versions: dict[str, tuple[Requirement, str | None]] = {}
    if not LOCK_PATH.exists():
        raise FileNotFoundError("requirements/lock.txt is missing")
    for raw_line in LOCK_PATH.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if raw_line.startswith(" ") or raw_line.startswith("\t"):
            continue
        try:
            req = Requirement(line)
        except Exception:
            logger.warning("Exception occurred", exc_info=True)
            # Skip entries that cannot be parsed as standard requirements.
            continue
        version = None
        for spec in req.specifier:
            if spec.operator in {"==", "==="} and not spec.version.endswith(".*"):
                version = spec.version
                break
        lock_versions[canonicalize_name(req.name)] = (req, version)
    return lock_versions


def _collect_requirements_from_txt() -> list[Requirement]:
    requirements: list[Requirement] = []
    if not REQ_TXT.exists():
        return requirements
    for raw in REQ_TXT.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        requirements.append(Requirement(line))
    return requirements


def _collect_requirements_from_pyproject() -> list[Requirement]:
    with PYPROJECT.open("rb") as handle:
        data = tomllib.load(handle)
    return [Requirement(dep) for dep in data.get("project", {}).get("dependencies", [])]


def verify_lock_alignment() -> None:
    """Ensure the lock satisfies requirements/base.txt and pyproject constraints."""
    lock_versions = _load_lock_versions()
    missing: list[str] = []
    mismatched: list[str] = []

    def _evaluate(requirements: Iterable[Requirement], source: str) -> None:
        for req in requirements:
            name = canonicalize_name(req.name)
            locked = lock_versions.get(name)
            if not locked:
                missing.append(f"{req.name} (from {source})")
                continue
            _, version = locked
            if version is None:
                continue
            try:
                ver = Version(version)
            except InvalidVersion:
                logger.debug("Exception caught, continuing", exc_info=True)
                continue
            if req.specifier and not req.specifier.contains(ver, prereleases=True):
                mismatched.append(f"{req.name}=={version} does not satisfy '{req}' from {source}")

    _evaluate(_collect_requirements_from_txt(), "requirements/base.txt")
    _evaluate(_collect_requirements_from_pyproject(), "pyproject.toml")

    problems: list[str] = []
    if missing:
        problems.append("Missing packages: " + ", ".join(sorted(missing)))
    if mismatched:
        problems.append("Version mismatches: " + ", ".join(sorted(mismatched)))
    if problems:
        raise RuntimeError("; ".join(problems))


def validate_pip_install() -> None:
    """Run pip install --dry-run to validate resolver compatibility."""
    cmd = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--dry-run",
        "--ignore-installed",
        "-r",
        str(LOCK_PATH),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        context = f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        raise RuntimeError(f"pip install dry-run failed\n{context}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Refresh requirements/lock.txt with validation")
    parser.add_argument(
        "--skip-compile",
        action="store_true",
        help="Skip uv pip compile and only enforce provenance + validation",
    )
    parser.add_argument(
        "--skip-validate",
        action="store_true",
        help="Skip the pip resolver dry-run step",
    )
    return parser.parse_args()


def ensure_provenance() -> None:
    """Guarantee the lock header is present when compile is skipped."""
    _inject_provenance_header(COMPILE_COMMAND)


def main() -> None:
    args = parse_args()
    steps: list[tuple[str, StepFn]] = []
    if args.skip_compile:
        steps.append(("Ensure provenance header", ensure_provenance))
    else:
        steps.append(("Generate requirements/lock.txt", generate_lockfile))
    steps.append(("Verify lock alignment", verify_lock_alignment))
    if not args.skip_validate:
        steps.append(("Validate pip resolver", validate_pip_install))

    any_failures = False
    for step_name, func in steps:
        success = run_step(step_name, func)
        any_failures = any_failures or not success

    if any_failures:
        sys.exit(1)


if __name__ == "__main__":
    main()
