#!/usr/bin/env bash
set -euo pipefail
# Coverage runner generated by codex_workflow.py
# Only add --cov flags if pytest-cov plugin is available.
if python - <<'PY'
import sys
try:
    import pytest_cov  # noqa: F401
except Exception:
    sys.exit(1)
PY
then
  pytest --cov=src --cov-report=term-missing "$@"
else
  echo "[run_coverage] pytest-cov missing; running plain pytest" >&2
  pytest -q "$@"
fi
