from typing import Awaitable, Callable

class Orchestrator:
    def __init__(self, callback: Callable[[str, str], Awaitable[str]], timeout_seconds: int = 60) -> None: ...
    def triage_failure(self, error_type: str) -> Awaitable[str]: ...
    def get_state(self) -> Awaitable[str]: ...