from typing import Awaitable, Callable, Dict, List, Tuple

class Orchestrator:
    def __init__(self, callback: Callable[[str, str], Awaitable[str]], timeout_seconds: int = 60) -> None: ...
    def triage_failure(self, error_type: str) -> Awaitable[str]: ...
    def triage_batch(self, error_types: List[str], max_concurrency: int = 4) -> Awaitable[List[Tuple[str, bool, str]]]: ...
    def get_state(self) -> Awaitable[Dict[str, str]]: ...
    def get_telemetry(self) -> Awaitable[Dict[str, int]]: ...