# Minimal Hydra config demonstrating a safe defaults list.
# This file is additive and does not alter live project configuration.
# Reference: https://hydra.cc/docs/advanced/defaults_list/

defaults:
  - _self_

train:
  max_steps: 5
  per_device_batch_size: 2
  dtype: bf16

# Usage:
#   python -m your_entrypoint +train.max_steps=10
# Or with overrides:
#   python -m your_entrypoint train.per_device_batch_size=1
