name: CI Workflow
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  _codex_guard:
    if: false

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - run: pip install black isort flake8
    - run: black --version && isort --version && flake8 --version
    - run: black --check .
    - run: isort --check-only --profile black .
    - run: flake8 .
    if: ${{ false }}
  type:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - run: pip install mypy
    - run: mypy --ignore-missing-imports .
    if: ${{ false }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - run: pip install -e .[dev] pytest pytest-cov
    - run: pytest -q --maxfail=1 --cov=src --cov-report=xml --cov-fail-under=80
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-xml-${{ matrix.python-version }}
        path: coverage.xml
    if: ${{ false }}
