name: CI Workflow

on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint (ruff --diff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Ruff
        run: ruff --diff

  type-check:
    name: Type-Check (mypy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run MyPy
        run: mypy .

  test:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run pytest
        run: pytest -q --maxfail=1

  coverage:
    name: Coverage (pytest + coverage)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run pytest with coverage
        run: pytest --cov=. --maxfail=1 --disable-warnings
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  sast:
    name: SAST (Bandit, Semgrep, Detect-Secrets)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bandit
        run: bandit -r .
      - name: Run Semgrep
        run: semgrep --config p/ci
      - name: Run Detect Secrets
        run: detect-secrets scan
