name: CI Workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint (ruff --diff)
    runs-on: [self-hosted, linux, codex]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Cache pip
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}
      - name: Install Ruff
        run: python -m pip install -U pip && pip install ruff
      - name: Run Ruff
        run: ruff --diff

  type-check:
    name: Type-Check (mypy)
    runs-on: [self-hosted, linux, codex]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Cache pip
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}
      - name: Install MyPy
        run: python -m pip install -U pip && pip install mypy
      - name: Run MyPy
        run: mypy .

  test:
    name: Tests (pytest)
    runs-on: [self-hosted, linux, codex]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Cache pip
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}
      - name: Install Pytest
        run: python -m pip install -U pip && pip install pytest
      - name: Run pytest
        run: pytest -q --maxfail=1

  coverage:
    name: Coverage (pytest + coverage)
    runs-on: [self-hosted, linux, codex]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Cache pip
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}
      - name: Install Pytest & Coverage
        run: python -m pip install -U pip && pip install pytest coverage
      - name: Run pytest with coverage
        run: pytest --cov=. --maxfail=1 --disable-warnings
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  sast:
    name: SAST (Bandit, Semgrep, Detect-Secrets)
    runs-on: [self-hosted, linux, codex]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Cache pip
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}
      - name: Install SAST tools
        run: python -m pip install -U pip && pip install bandit semgrep detect-secrets
      - name: Run Bandit
        run: bandit -r .
      - name: Run Semgrep
        run: semgrep --config p/ci
      - name: Run Detect Secrets
        run: detect-secrets scan

# BEGIN: CODEX_CI_MANUAL
on:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install black isort flake8
      - run: black --version && isort --version && flake8 --version
      - run: black --check .
      - run: isort --check-only --profile black .
      - run: flake8 .

  type:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install mypy
      - run: mypy --ignore-missing-imports .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install -e .[dev] pytest pytest-cov
      - run: pytest -q --maxfail=1 --cov=src --cov-report=xml --cov-fail-under=80
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-xml-${{ matrix.python-version }}
          path: coverage.xml
# END: CODEX_CI_MANUAL
