name: codex-self-manage

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  ci:
    if: github.event_name == 'workflow_dispatch' || contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ' '), 'codex-ci')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.12'
      - name: Install project + tools
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pre-commit pytest coverage pip-audit
      - name: Pre-commit (all files)
        run: pre-commit run --all-files
      - name: Tests (with coverage)
        run: |
          coverage run -m pytest -q
          coverage xml
      - name: Dependency audit (pip-audit)
        run: |
          pip-audit -r requirements.txt || true
          pip-audit || true
      - name: Codex CLI audit (log)
        run: python tools/codex_cli.py audit
        env:
          CODEX_CLI_SKIP_PRECOMMIT: "1"
          CODEX_CLI_SKIP_TESTS: "1"
